### ISSUE TITLE
CutBeamByBeamData: specify weldsize and operation name

### ISSUE THREAD

**Issue by BouwenmetStaal** [idea-statica/iom-examples#1]
https://github.com/idea-statica/iom-examples/blob/5cf9ed59b34cd7a44b2308df1eacc921cc40a91b/IdeaStatiCa.Codes/Example.cs#L156

For the CutBeamByBeamData operation:

1. How can I specify the weldsize?
2. And is it possible to specify a custom name for the operation instead of "Cut Beam by Beam X"?

![image](https://user-images.githubusercontent.com/48355355/66836721-277f5300-ef62-11e9-8553-a7ab06a8b7f3.png)

**Comment by mpospisil** [comment]
If the problem remains in the latest version- reopen it.
