### ISSUE TITLE
Object of type 'IdeaRS.OpenModel.OpenModel' cannot be converted to type 'IdeaRS.OpenModel.OpenModel'

### ISSUE THREAD

**Issue by kniazmajowiec** [idea-statica/iom-examples#11]
I am sorry if the question is too simplistic. I am starting with using C# and IOM in VS Code.
While running IOM.SteelFrameDesktop project I encounter the following error:

_Object of type 'IdeaRS.OpenModel.OpenModel' cannot be converted to type 'IdeaRS.OpenModel.OpenModel'_
...
_at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)_

I understand that it is connected with the assemblyBinding section of the App.config
I am using IdeaRS.OpenModel 10.1.0.2 so I expected that default line
_bindingRedirect oldVersion="0.0.0.0-10.2.0.0" newVersion="10.1.0.2" /_
should work. However, it does not.
I would be grateful for help

**Comment by TekuSP** [comment]
Can you provide solution folder with problem you are encountering?

**Comment by kniazmajowiec** [comment]
In the attachment, you can find the folder. I have changed the code to use it in VS Code. 
Thanks for help and Merry Christmas

[Idea_Desktop_GItHub.zip](https://github.com/idea-statica/iom-examples/files/4002316/Idea_Desktop_GItHub.zip)

**Comment by TekuSP** [comment]
I will look into issue, in meanwhile, please provide me this information:
**Desktop (please complete the following information):**
 - OS: [e.g. Windows 7, Windows 8, Windows 10-1903, Windows 10-1803]
 - IOM Version [e.g. 10.0, 10.1]
 - IdeaStatiCa Version [e.g. 10.0, 10.1]


Thank you and Merry Christmas

**Comment by TekuSP** [comment]
I cannot reproduce your problem using my build configuration.

Can you provide .vsbuild folder too? What build addon do you use for VS Code?

**Comment by kniazmajowiec** [comment]
Currently, I do not have access to the working computer. 
At work I am using Windows 10,
IOM 10.1.02
and Idea Statica 10.1 (94.54235)

Do I understand that the code works correctly with your settings?

**Comment by TekuSP** [comment]
Yes, code you provided works correctly in Visual Studio 2019 and Visual Studio Code.

**Comment by mpospisil** [comment]
You can try to remove  IdeaRS.OpenModel from our nuget, delete assembly binding in app.config and add reference to IdeaRS.OpenModel.dll which is in your ideastatica installation directory. Before rebuilding your app delete all obj and bin directories to be sure it will be rebuilt with the correct dlls.

**Comment by TekuSP** [comment]
> Currently, I do not have access to the working computer.
> At work I am using Windows 10,
> IOM 10.1.02
> and Idea Statica 10.1 (94.54235)
> 
> Do I understand that the code works correctly with your settings?

And latest version is IDEA StatiCa 10.1.113. There can be missversion between IOM and Statica version.

**Comment by kniazmajowiec** [comment]
Sorry for late response and thank you for your help. 
Your advices helped me  find my problem:
I had to add net48 as TargetFramework. netcoreapp3.0, that worked with webservice was not enough.
I understand that it is rather rookie mistake, at least I learnt something.
