### ISSUE TITLE
[QUESTION] Names of plates in OpenModel and ConnectionsDataResulst not equal

### ISSUE THREAD

**Issue by BouwenmetStaal** [idea-statica/iom-examples#13]
Is your question related to a problem? Please describe.

I want to make an optimization algorithm where the thickness of the plates in a connection are optimized. The algotrithm will calculate the connections, check the results of the plates and increase failing plates (start easy).

It will check the results in the class ConnectionDataResults and after make changes to plate thickness in the open model.

But the name of a plate in ConnectionDataResults ("Plate 1")  is not equal to Openmodel ("P1"). Therefore, you cannot "find the correct plate" and apply the plate thickness increase.

Describe the solution you'd like
Include identical names in both classes. Or use unique ID's.

Quickwatch Openmodel
![image](https://user-images.githubusercontent.com/48355355/72143715-8143bd80-3397-11ea-87fd-f7f5a15800fb.png)

Quickwatch ConnectionDataResults
![image](https://user-images.githubusercontent.com/48355355/72143737-886acb80-3397-11ea-9f99-19eaaf9cdc1e.png)

**Comment by mpospisil** [comment]
we will look at this during the bugfixing - in the week from Jan 24th
