### ISSUE TITLE
[QUESTION] Select boltsize

### ISSUE THREAD

**Issue by BouwenmetStaal** [idea-statica/iom-examples#14]
What is the appropriate way to select a different bolt size? 

For example M30.

https://github.com/idea-statica/iom-examples/blob/913b494b8b4a7c295db512e4ccffd64b679b47bb/IdeaStatiCa.Codes/Example.cs#L166-L180

**Comment by mpospisil** [comment]
we will look at this during the bugfixing - in the week from Jan 24th

**Comment by vadura-pavel** [comment]
Hello,
open model allow define any size of bolt, even non standard. However, if you want work with standard sizes, easy way is use IDEA StatiCa Connection. In Ribbon tab Materials you can find specification of bolt to see on picture.
![boltIOM](https://user-images.githubusercontent.com/51780315/74220283-768a8a00-4caf-11ea-9ca4-89ad49219e6e.png)

**Comment by BouwenmetStaal** [comment]
Hi Pavel,

Can you tell me which of the properties are used for calculation in IDEA?

I would assume that:
-Head diameter
-Head diagonal diameter
-Head height
-Nut  thickness 
-Washer thickness
, are not needed for calculation and therefore do not need to be defined.

Please let me know whether I'm correct or not.

BR,
Rayaan

**Comment by dkolaja** [comment]
Hi Rayaan

- Head diameter
-Head diagonal diameter
-Washer thickness
-Nut thickness
Are necessary for caculation of bolt stiffness

-Head height
Is used just for presentation

Greetings

Drahos

**Comment by BouwenmetStaal** [comment]
And what about:
 	BoreHole = 0.018, 
 	AnchorLen = 0.05, 

Do they need to be defined?
