### ISSUE TITLE
[QUESTION]Beam cut data has wrong normalVector

### ISSUE THREAD

**Issue by errone92** [idea-statica/iom-examples#15]
Hello. I've noticed in exporting the connection data that when there are cuts that are at an angle (i.e. not directly in X, Y, or Z axis of the connection) the output normalVector does not make sense. For example in the connection shown below M6 is cut at an angle about the Z-axis by a Shifted End Plate. 
![MemberCut](https://user-images.githubusercontent.com/46051037/72971488-0e403b00-3dca-11ea-8db3-45cb24cf37b1.PNG)
However, the data exported shows the normalVector as:
![MemberCut_vector](https://user-images.githubusercontent.com/46051037/72971618-4e072280-3dca-11ea-9ffa-33e082e1ce2e.PNG)
Which does not make sense as this is pointing in the wrong direction. This causes the cut to be placed wrong when I try to translate it to a fitting in Tekla Structures.
![MemberCut_Tekla](https://user-images.githubusercontent.com/46051037/72971997-edc4b080-3dca-11ea-83a6-314ee642844d.PNG)

Is this a problem with the API? Or perhaps beam cuts use a different coordinate system than the connection? I'll attach the file below.

[ComplexConn1.zip](https://github.com/idea-statica/iom-examples/files/4102265/ComplexConn1.zip)

**Comment by mpospisil** [comment]
in our new version 20 - which will be released in April there it the new feature which allows to define members by its direction vector (its coordinate system). It also allows to have direction vector oriented to the connection. It simplifies inports/exports.

If you want - we can provide you the beta version for your development.

**Comment by errone92** [comment]
Sounds great. Yes I would appreciate having the beta for testing.

**Comment by mpospisil** [comment]
I will prepare a version the next week. Send me your email - I will send you details.

**Comment by errone92** [comment]
You can send it to e.estrado@oostingh.nl. Thanks!

**Comment by errone92** [comment]
> I will prepare a version the next week. Send me your email - I will send you details.

Hello Martin. Were you able to prepare the beta for testing?

**Comment by mpospisil** [comment]
Hi, we are working on it. I'm sorry for delay.

**Comment by mpospisil** [comment]
I've just sent you a link for downlond beta version. The source code of updated examples are in the branch beta-ver20

https://github.com/idea-statica/iom-examples/tree/beta-ver20
