### ISSUE TITLE
[QUESTION] ConnectedIds from welds are not the id from the beams

### ISSUE THREAD

**Issue by GRamsaroep** [idea-statica/iom-examples#16]
Hi,

When i try to get the info out of the connectedids from the WeldData class, it gives the results of the "OriginIds" form the beams and not the unique ids. This is kind of confusing when i try to get the right object to being connected to the other one. This probably can be changed in the API? 

For example:

Members M1, M2, M3 has different unique ids, but all the same Originids. With plates it works but not with the beams at the moment.

EDIT: Probably the same problem with the bolts, but most of the bolts goes throuhg plates. Not tested yet if the bolts shows the originids or the unique ids.

**Comment by mpospisil** [comment]
Can you attach me project - to be sure we are talking about same. We will look at it

**Comment by GRamsaroep** [comment]
[connectionFromIOM-local.zip](https://github.com/idea-statica/iom-examples/files/4184663/connectionFromIOM-local.zip)

**Comment by GRamsaroep** [comment]
Its probably the ids that are made first. I made beams/members a several time.  I deleted them and made them again so the ids weren't from the beginning anymore like member 1 = id 1.  Now its like member 1 = id 4. Maybe that helps to figure the problem out in the api bug.

**Comment by GRamsaroep** [comment]
any news about the bug?

**Comment by vadura-pavel** [comment]
Hi,
connectedids from the WeldData using primary OriginalModelId (https://idea-statica.github.io/iom/iom-api/latest/html/P_IdeaRS_OpenModel_Connection_BeamData_OriginalModelId.htm). In case if OriginalModelId doesn’t exist or is empty is used Id. So for you will be great if you correctly fill unique OriginalModelId in beamData.

**Comment by GRamsaroep** [comment]
I dont understand what you mean exactly. Because both OriginalID and id are not empty, but mutiple objects(members) has the same originalID, but unique ids.

This is the ouput from the project i made as a test.

Member 4 id= 4 , but OriginalID = 2
Member 3 id = 3, but OriginalID = 2
Member 2 id = 2, but OriginalID = 2

I dont know why IDEA gives those members all the same OriginalIDs.

**Comment by vadura-pavel** [comment]
Hi,
_Because both OriginalID and id are not empty, but mutiple objects(members) has the same originalID, but unique ids._ - This is the problem. OriginalID cannot be same. IDEA do not generate OriginalID - its came from import.
I assume you work with ideaCon file which was created from previous import. Am I right? So problem is in first import IOM model to IDEA.

**Comment by GRamsaroep** [comment]
Yes, now I understand the problem. Thank you very much. It is indeed a project made from the IOM model. Thanks again!
