### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by BouwenmetStaal** [idea-statica/iom-examples#17]
Hi IDEA team,

I created a grasshopper component that calculations an IDEA file, by using its file path:
https://github.com/BouwenmetStaal/KarambaIDEA/blob/BMSHackathon/KarambaIDEA/6.%20IDEA%20utilities/CalculateIDEAFile.cs

It uses the following code to do the hidden calculation:
https://github.com/BouwenmetStaal/KarambaIDEA/blob/BMSHackathon/IDEA/HiddenCalculation.cs

My problem is that the script only works when IDEA Statica has been opened. If IDEA is not opened it does not work. This can be confusing for users of the Grasshopper component.

How can I solve this? Am I missing a part of code/ is there a method that opens IDEA on the background?

BR,
Rayaan

**Comment by mpospisil** [comment]
It is not the expected beaviour.  We will investigate this issue.

**Comment by mpospisil** [comment]
I wasn't able to reproduce it on my PC. Write me a private email - we can plan a web meeting.

**Comment by mpospisil** [comment]
Have you checked the check box "REMEMBER ME" when you log in into Idea Connection app ?
It seems only you report this problem.

**Comment by BouwenmetStaal** [comment]
Hi Martin,

I have set a workable hard-coded example for you to test.

It can be found here:
https://github.com/BouwenmetStaal/KarambaIDEA/tree/BMSHackathon

Open it, set "Tester" as startup project.
When IDEA has not been opened results will not be generated in the hidden calculation:

https://github.com/BouwenmetStaal/KarambaIDEA/blob/44ec63c5cd70af754d3c11cfdd3a2c68d0f3a363/IDEA/HiddenCalculation.cs#L225

**Comment by mpospisil** [comment]
We have improved our licencing a lot. Can you check it with our release actuall 20.00
