### ISSUE TITLE
BeamData has no Profile type/name in the class[FEATURE]

### ISSUE THREAD

**Issue by GRamsaroep** [idea-statica/iom-examples#19]
**Is your feature request related to a problem? Please describe.**
In the beamData class there is no info about the beam profile. It only shows plates where the beam is made of, but not the profile name.

**Describe the solution you'd like**
A extra add on in the class where the name of the profile is exported also in the IOM when using the conData of a project.

**Describe alternatives you've considered**
Its possible to check the thickness of the web and flange to know what profile it is, but that will be extra work while its already defined in IDEA in the project.

**Comment by mpospisil** [comment]
it sjould be fixed - we will prepare an example

**Comment by mpospisil** [comment]
see interface

https://github.com/idea-statica/ideastatica-plugin/blob/release-21.0.0-beta/IdeaStatiCa.Plugin/IConnHiddenCheck.cs

where is the new method

string GetAllConnectionData(string connectionId);

which return XML string wich represents the instance of IdeaRS.OpenModel.OpenModelContainer

https://github.com/idea-statica/iom/blob/master/IdeaRS.OpenModel/OpenModelContainer.cs

from this instance you can get information geometry of the connection as well as information about FE analysis
