### ISSUE TITLE
Retrieve ConnectionResults

### ISSUE THREAD

**Issue by BouwenmetStaal** [idea-statica/iom-examples#2]
https://github.com/idea-statica/iom-examples/blob/5cf9ed59b34cd7a44b2308df1eacc921cc40a91b/IOM.SteelFrameDesktop/Program.cs#L52

How can I execute the hidden calculation on my finalized model and retrieve the ConnectionResults, like the unity checks?

I guess these methods found in the documentation of the v10.1 API are needed:
IdeaRS.OpenModel.Connection.CheckResBolt()
IdeaRS.OpenModel.Connection.CheckResPlate()
IdeaRS.OpenModel.Connection.CheckResWeld()

**Comment by mpospisil** [comment]
This function is not public now. We will make it public in the next patch.

**Comment by mpospisil** [comment]
I have added the new example - ConnectionHiddenCalculation in the branch conn-hidden-calc - it shows how to run CBFEM from any .NET application. The example requires the patch of Idea StatiCa v10.1 which should be released in Novemeber 2019. But if you need it earlier I can provide unofficial version for testing - send just send me a mail.

**Comment by BouwenmetStaal** [comment]
Can you send the unofficial version (for testing) to rayaan@bouwenmetstaal.nl ?
