### ISSUE TITLE
[FEATURE] Beam end offsets

### ISSUE THREAD

**Issue by errone92** [idea-statica/iom-examples#20]
**Is your feature request related to a problem? Please describe.**
It would be good to be able to obtain the beam end offsets (ex, ey, ez) when reading geometry from an IdeaCon file. This will greatly help with finding the correct connection point when exporting so that the other elements (plates, bolts, etc.) are placed correctly. Basing the connection point off of only member centrelines or manual selection leads to inaccuracies.

**Describe the solution you'd like**
It should be a property of the BeamData class.

**Describe alternatives you've considered**
Knowing the connection position (start, end, centre) would also be helpful it obtaining the right connection point.

**Comment by mpospisil** [comment]
In the next version we plan to improve the export of connections from our application. We want to have a general solution.
