### ISSUE TITLE
[QUESTION] serviceUrl for IDEA Statica RCS calculations

### ISSUE THREAD

**Issue by OlegrodMEG** [idea-statica/iom-examples#21]
Dear all,

I am looking for the serviceUrl where I can sent the RCS-calculation .xml file to. The example indicates that[https://viewer.ideastatica.com/ConnectionViewer/CreateFromIOM](https://viewer.ideastatica.com/ConnectionViewer/CreateFromIOM ) is the way to go. However, I get a Error500. Looking into [https://viewer.ideastatica.com](https://viewer.ideastatica.com), I suspect that it is because I am not using a Connection calculation. I would like to know how to proceed.

Kind regards,

**Comment by mpospisil** [comment]
RCS projects are not supported by our cloud services now
