### ISSUE TITLE
[QUESTION]Crosssectionfactory for plates

### ISSUE THREAD

**Issue by BouwenmetStaal** [idea-statica/iom-examples#22]
Hi,

Does the class `CrossSectionFactory` in `IdeaRS.OpenModel.CrossSection.CrossSectionFactory` also contain a method to create plate section (height and width?

I could not find it.

BR,
Rayaan

![image](https://user-images.githubusercontent.com/48355355/80681344-cd3e7d80-8ac0-11ea-9864-4fc94f18c943.png)

**Comment by tLuber72** [comment]
For this type of CrossSection you can use
	CrossSectionFactory.FillRectangle(cssO, 0.03, 0.005);

BR
Tomas Luber
