### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by kbroeders** [idea-statica/iom-examples#23]
Hi IDEA Team,

When I run the HiddenCalculation file I get no results.
See the picture below?

![image](https://user-images.githubusercontent.com/65399362/82680410-81f53600-9c4c-11ea-94ad-bf3bedb757f7.png)

Are these results empty because I'm missing something?

I haven't changed anything to the file. The Geometry works fine.

BR,
Koen

**Comment by mpospisil** [comment]
Hi Koen,

can you attach your ideacon project file ?

BR,
Martin

**Comment by kbroeders** [comment]
Hi Martin,

I tried it with both of the files that you can find in: https://github.com/kbroeders/IS_connection
And both of them only gives the geometry and not the calculation results.

BR,
Koen

**Comment by mpospisil** [comment]
IS v 20.0 has been released as well as Idea nuget packages. I believe it will work.
