### ISSUE TITLE
[QUESTION] Report and Stiffness

### ISSUE THREAD

**Issue by kbroeders** [idea-statica/iom-examples#25]
Hi IdeaStatica, 

I was wondering if it is possible to also calculate the stiffness analysis of the connection, and if it is possible to print a report with IOM.  For both cases I would like some examples on how to do this if possible.

BR,

Koen Broeders

**Comment by mpospisil** [comment]
It is not possible now. We will discuss this issue internally and I will let you know.

**Comment by kbroeders** [comment]
Thanks a lot

**Comment by mpospisil** [comment]
We don't have any capacity to implement it within 6 months. Can you explain us your usecase ? We will set priority to this task according to it.

**Comment by kbroeders** [comment]
I want to do an optimization loop where I use RFEM and IdeaStatica and I want the stiffness from IS to put back into RFEM and in the end a report of the final connection.

**Comment by vojtech-chalupa** [comment]
Hello, a quick update. We are looking into expanding the capabilities of IOM and this feature is now in the planning phase.

**Comment by khameeteman** [comment]
Hi @vojtech-chalupa , I am also looking for the "report" feature. 

> this feature is now in the planning phase

Is this about the "report" feature? Any update on this?

**Comment by vojtech-chalupa** [comment]
Hello, we are currently targetting the autumn release (21.1) with the report feature.

**Comment by paolobia** [comment]
> Hello, we are currently targetting the autumn release (21.1) with the report feature.

YEP GOOD NEWS !!!
