### ISSUE TITLE
[BUG] No weld connected parts data from SP and PCUT

### ISSUE THREAD

**Issue by errone92** [idea-statica/iom-examples#26]
Hello. I've noticed that when a connection is made using a Stiffening Plate (SP) and welded to a member using a Cut of Plate (PCUT) operation, in the welds of the exported geometry the ConnectedPartIds property is always missing the ID of the plate.

In the attached file when you look at the ConnectionData you see that in the connectedPartIds of the weld it shows "1" which is the ID of the member M1 but an empty string where the ID of the plate ("10") should be (See screenshot below).

![image](https://user-images.githubusercontent.com/46051037/85842336-db96d600-b79f-11ea-90ae-794fc3fb644a.png)

 - OS: Windows 10-1809
 - IOM Version 20.0.16
 - IdeaStatiCa Version 20.0.80.57220
[Gusset test.zip](https://github.com/idea-statica/iom-examples/files/4836106/Gusset.test.zip)

**Comment by vadura-pavel** [comment]
Hello,
Thank you for reporting bug. 
Problem was solved and fix of this problem will be available in next patch of version V20.
