### ISSUE TITLE
[BUG]OriginSettings not appear in idea statica v20

### ISSUE THREAD

**Issue by dataneodev** [idea-statica/iom-examples#29]
OriginSettings like project name or author not appear in idea statica v20, 
in previous versions idea statica it worked.

```
model.OriginSettings = new OriginSettings();

model.OriginSettings.ProjectName = "Project";
model.OriginSettings.Author = "GK";
model.OriginSettings.ProjectDescription = "Test project";
```

**Comment by vadura-pavel** [comment]
Thank you for reporting bug.
Problem was solved and fix of this problem will be available in next patch of version V20.
