### ISSUE TITLE
How to get the info out of an project?

### ISSUE THREAD

**Issue by GRamsaroep** [idea-statica/iom-examples#3]
Hello,

I was wondering if its possible to get the information out of the IDEA file. Now the example shows how to input information in a project, but is there a way to get the information out of IDEA? Example:
Get the dimensions of the calculated connection and put it back into a excel file for example or a text file.

Regards,

Giorgio

**Comment by mpospisil** [comment]
Hello Giorgio
function for output is not public now we will make it public in a next patch

**Comment by GRamsaroep** [comment]
Is there any indication of when the next patch will come?

**Comment by mpospisil** [comment]
I have added the new example - ConnectionHiddenCalculation in the branch conn-hidden-calc - it shows how to run CBFEM from any .NET application. The example requires the patch of Idea StatiCa v10.1 which should be released in Novemeber 2019. But if you need it earlier I can provide unofficial version for testing - send just send me a mail.

**Comment by GRamsaroep** [comment]
I will wait for the patch. I assume the patch will add more possibilities for the IOM and expand the classes with more input possibilities.
