### ISSUE TITLE
[BUG]Bolts are connected to the same profile flange

### ISSUE THREAD

**Issue by dataneodev** [idea-statica/iom-examples#30]
I added 2 groups of bolts in open model. Both are connected to the same profile and separate plates.

`boltGrid.ConnectedPartIds = new List<string>() { beam2Data.OriginalModelId, plateData.OriginalModelId };`

Both groups of bolts are connected to the top flange.

Is this a bug?

![image](https://user-images.githubusercontent.com/38402428/88815899-21d6bf00-d1bc-11ea-975d-00ab4a4354f7.png)

**Comment by vadura-pavel** [comment]
Hi,
there is more aspect which affects connected Parts of bolt grids. For example, axis of local coordinate system and anchor length. Can you send IOM model with your problem? I will fix model and send you back.

**Comment by mpospisil** [comment]
added to development

**Comment by mpospisil** [comment]
It is not a bug - you can not specify the length of the bolts but you must set the correctly. See the this example - there is the bolt grid which connects 4 plates but no bolts for individual endplates

![image](https://user-images.githubusercontent.com/19650653/96622388-28338d80-130a-11eb-96d6-82415faaa1bd.png)

[bolt-grid.zip](https://github.com/idea-statica/iom-examples/files/5410397/bolt-grid.zip)
