### ISSUE TITLE
Country Code

### ISSUE THREAD

**Issue by GerryArk** [idea-statica/iom-examples#31]
I am writing a plugin to our FEM Application

I have setup all the relative data and set the   OpenModel.OriginSettings.CountryCode 
to the relative country code

Based on the country code  the relative material types have been generated 

The model comes up always in EuroCodes   

What am I missing here ?   

thanks
Gerry D'anza
ixRay tld

**Comment by mpospisil** [comment]
Hi Garry,

can you assign your iom model (xml file) - we will look at it

Martin

**Comment by GerryArk** [comment]
Hi Martin

Sample file  in attachment
When I run ideastatica it starts as EC

regards
Gerry D'Anza



------ Original Message ------

**Comment by mpospisil** [comment]
Gerry, I can't find any attachment.

**Comment by GerryArk** [comment]
Hi Martin
here they are

gerry

------ Original Message ------

**Comment by GerryArk** [comment]
Dear Martin

I have already implemented  the connection to CCM
but now I donìt see how to add the load cases and loads to the joints




Gerry D'Anza Architect

CEO ixRay ltda
Dr.Emilio Frugoni
1109 Montevideo
11200 Uruguay





------ Original Message ------
From: "gerry" <gerry@forten32.com>
To: "idea-statica/iom-examples" 
<reply@reply.github.com>
Sent: 8/10/2020 11:09:22 PM
Subject: Re[2]: [idea-statica/iom-examples] Country Code (#31)

**Comment by mpospisil** [comment]
Gerry,

loading is taken from your IOM - see

https://idea-statica.github.io/iom-examples/iom-steel-connections/steel-frame1.html


all is described there

Martin

**Comment by GerryArk** [comment]
Hi Martin

Nice that will help a lot

Gerry D'Anza Architect

CEO ixRay ltda
Dr.Emilio Frugoni
1109 Montevideo
11200 Uruguay





------ Original Message ------
