### ISSUE TITLE
XML connection example

### ISSUE THREAD

**Issue by atirsoftware** [idea-statica/iom-examples#32]
Hi,

I work for ATIR software development and we have an analysis FEM software called STRAP.
We would like to offer the option to export Steel connection from STRAP to idea using XML file.
Can you send me an example of an XML file (that can be imported into IDEA) that includes 3D connection with multiple members and member properties?

Thanks,
Ehud.

**Comment by mpospisil** [comment]
Hi Ehud,

we have the example

https://idea-statica.github.io/iom-examples/iom-steel-connections/steel-frame1.html

which includes also xml generated  

https://github.com/idea-statica/iom-examples/tree/master/IOM_SteelFrame1/IOM.GeneratorExample/SampleFiles
