### ISSUE TITLE
[FEATURE] loadbar pop up screen for the hidden calculation

### ISSUE THREAD

**Issue by BouwenmetStaal** [idea-statica/iom-examples#33]
I would like to have the possiblity to display a loadbar that gives insight on the status of the IDEA calculation.

Is something like that possible?

**Comment by mpospisil** [comment]
the hidden calculator can send messages about a progress of a calculation (as you can see in IdeaStatiCa CCM). The client (in this case our example) needs to be registered for notifications. We will have to adapt the source code of the example.

**Comment by vojtech-chalupa** [comment]
Closing this issue, it is considered to be resolved. Feel free to reopen.
