### ISSUE TITLE
[BUG] No connectedPartIds in weld data

### ISSUE THREAD

**Issue by errone92** [idea-statica/iom-examples#34]
#26 
Hi coming from the previous issue 26 I installed the new IDEA StatiCa patch version 20.0.104.57553. Unfortunately, this problem is still not resolved. In fact it is worse. Now not only does connectedPartIds have an empty string when it is a Stiffening Plate (SP) but for all other welds it gives "null". Now all connections have null part ids for the welds. I have tried resaving with the new version as well as remaking the connection from scratch. No luck. I attached the ideaCon file and the JSON output text file.

[Gusset Test V20.0.104.zip](https://github.com/idea-statica/iom-examples/files/5089105/Gusset.Test.V20.0.104.zip)

**Comment by Basnederveen** [comment]
I have the same problem.

**Comment by mpospisil** [comment]
added to development

**Comment by mpospisil** [comment]
This issue is fixed but it will be released in version 21 - together with other improvements of export of connection geometry. Version 21 will be released in April 2021 but if you want we can provide you the beta version for development of your plugin.
