### ISSUE TITLE
Export information about LCS of members

### ISSUE THREAD

**Issue by nolf86** [idea-statica/iom-examples#35]
Hi,

I'm working on importing Idea connection to other program.
I'm struggling with Beams, since they are made of Plate elements and don't have property normally associated with Beams like:
-Beams start
-Beam end
-Beam orientation
Of course I can import them as a plates but I need to represent them as a native beams in other software.

It would be much easier to import beams from Idea connection if BeamData type had a property:  Beam.Start, Beam.End and Beam.AxisX, Beam.AxisY, Beam.AxisZ.

Thanks,
M.J.

**Comment by vadura-pavel** [comment]
Hi,
we know about this issue and next version v21 will be problem solved.

**Comment by mpospisil** [comment]
see interface

https://github.com/idea-statica/ideastatica-plugin/blob/release-21.0.0-beta/IdeaStatiCa.Plugin/IConnHiddenCheck.cs

where is the new method

string GetAllConnectionData(string connectionId);

which return XML string wich represents the instance of IdeaRS.OpenModel.OpenModelContainer

https://github.com/idea-statica/iom/blob/master/IdeaRS.OpenModel/OpenModelContainer.cs

from this instance you can get information geometry of the connection as well as information about FE analysis
