### ISSUE TITLE
[QUESTION] How to make a plate by plate cut and plate by beam top flange cut?

### ISSUE THREAD

**Issue by BouwenmetStaal** [idea-statica/iom-examples#36]
How can you make a plate by plate cut and plate by beam top flange cut in the API?

For the web widener found in the picture below I want to create a weld between the widener and the endplate [blue].
And I want to create a weld between the widener and the topflange of the i-sections [red].

As far as I've seen the current example only covers beam by beam cuts and beam by plate cuts.

![image](https://user-images.githubusercontent.com/48355355/91460592-43dd6300-e888-11ea-9a36-25372c4ca17a.png)

**Comment by vadura-pavel** [comment]
Hi,
at the moment we don’t support cutting plate by plate. However, this feature is in plan for new version IDEA StatiCa. 
For now you need to create properly plate (set geometry how should be after cutting) and two welds.

**Comment by BouwenmetStaal** [comment]
Hi pavel,
In my case the geometry of the plate is as it needs to be.
How can I add welds between the plates in the API (as you mentioned)?
BR

**Comment by vadura-pavel** [comment]
Hi Rayaan,
look at https://idea-statica.github.io/iom-examples/iom-steel-connections/steel-frame1.html in section about Welds. In property ConnectedPartIds just add two idenfificators of plates and thats all. Bacicaly you can weld member/member, member/plate or plate/plate.

**Comment by BouwenmetStaal** [comment]
Hi Pavel, 
I am facing some difficulties, can we plan a meeting to cover these hurdles?
BR

**Comment by BouwenmetStaal** [comment]
One of the questions I have is for the ConnectedPartIds, how can you distinguish the ids of plates with the Ids of beams. The OriginalModelIds do not seem to be unique ids. 
Therefore in my case, the weld is created between the plates.

Second, is defining a start and end point of the weld necessary?

![image](https://user-images.githubusercontent.com/48355355/91991857-bab8a700-ed33-11ea-85cd-715c3174236f.png)

**Comment by vadura-pavel** [comment]
Hi Rayaan,
beams and plates are distinguishing by OriginalModelId. When we created link between some CAD app and IDEA StatiCa, we read the identification from these CAD programs which guarantee unique ID. So in your case you can generate OriginalModelId for example like “Plate{ID}” – {ID}( – you replace by id of current plate)  and same way in case of beam “Beam{ID}”.
For summary in to ConnectedPartIds you must add OriginalModelId which is unique.
Definition of start point, and end point of weld is not necessary. You can put same value into start point and end point. This value should represent point which pointing on edge of first plate and surface of second plate.
If you need help, send me email and we will arrange a meeting.

**Comment by BouwenmetStaal** [comment]
Hi Pavel,

Thanks, I've send you a meeting invite.

Topics I want to cover
-The weld between the widener and beam flange.
-Error when the same "programmed template" is used in truss structure project.

Best


![image](https://user-images.githubusercontent.com/48355355/92206028-22cbd200-ee87-11ea-95d8-8226a27493a3.png)
