### ISSUE TITLE
[QUESTION] Possible values of Id's for BeamData

### ISSUE THREAD

**Issue by jorgebslu** [idea-statica/iom-examples#37]
Hi,
I am experiencing issues when I try to export an iom.xml file formed by just the main members of a simple beam-to-column connection to Idea Connection 20.0.104.57553 through IdeaStatica.Plugin.dll API.
It seems like the issue is related to `OriginalModelId`.
According to the [documentation](https://idea-statica.github.io/iom/iom-api/latest/html/P_IdeaRS_OpenModel_Connection_BeamData_OriginalModelId.htm) "_Get or set the identification in the original model In the case of the imported connection from another application_" , it is a string type, so "any" string should be possible.
From our application, I have tried to set the following values (for example, for the beam) and the member was not exported to Idea Connection:
- Case 1
```csharp
Id = 1.
OriginalModelId = "122a59e3-fa56-4cd5-8a79-a9ec83719ec9"
```
- Case 2
```csharp
Id = 2.
OriginalModelId = "7"
```

- Case 3
```csharp
Id = 1.
OriginalModelId = "Bar-1"
```

**The case I am able to succeed is:**
```csharp
int myId = member.MemberId.Id;
Id = myId.
OriginalModelId = myId.ToString()
```

Could you please provide me the allowed/required values for `BeamData.OriginalModelId` property?
Do these Id's have any relation with those defined in the `ConnectionMember` objects in `ConnectionPoint` object? 
Could you also take a look at [iom77.zip](https://github.com/idea-statica/iom-examples/files/5207744/iom77.zip) file, where only the column is exported to Idea Connection.

Thank you in advance.

**Comment by mpospisil** [comment]
Hi

The purpose of this property is to have an users tag which can link members in connection project with memebers in FEA model - it can be any sting value. Unfortunatelly  we have more usecases where we use this property in our applications and there is the bug when we import create idea connection project directly from an users's iom. The values seems to be lost during import. I've created a bug in and we will fix it in the next version.

**Comment by mpospisil** [comment]
Hi Jorge,

I'm sorry it is still in our backlog. 

Martin

**Comment by mpospisil** [comment]
We have tested it and the value originalModelId corresponds to value in exported instancer of ConnectionData

![image](https://user-images.githubusercontent.com/19650653/122389952-c3503600-cf71-11eb-8164-acd22fe11b38.png)
