### ISSUE TITLE
BIM link is still operational 20.0 with with "Iper Space BIM 3.x" ?

### ISSUE THREAD

**Issue by ThierryLaroche** [idea-statica/iom-examples#39]
hello

our Italian subsidiary asks to sell a renewal (for AdvanceDesignConnection 20) to one of their customer if the BIM links with Iper Space BIM 3.x (a FEM software) developped by Soft Lab develop is still operational

as ADC and IdeaConnection differ only by colors, name and icon, we are quite sure this link still works but we'd like to be sure
maybe the only problem would come from the installation in a different folder

thanks in advance
Thierry LAROCHE
GRAITEC Innovation

**Comment by mpospisil** [comment]
Thierry,

You right - ADC and IdeaConnection have only different UI style - ADC which is compatible with IS v20.0 has the same features.
Have you upgraded your link to be compatible with our new API ? If not I would strongly to recomment this upgrade. The old API is not supported any more and new one is much more stable. If you have any questions - contact us directly. We can plan a web meeting to help you to upgrade your application to be fully compatible with the latest IS.

Martin
