### ISSUE TITLE
[BUG] Region for circular plate (PlateData)

### ISSUE THREAD

**Issue by jorgebslu** [idea-statica/iom-examples#40]
Hi
I need to define a circular PlateData.
Thickness = 10 mm
Diameter = 60 mm
Location: any
I am using 4 consecutive arcs.

```xml
<PlateData>
  <Id>24</Id>
  <Name>plate 24 (anchor plate)</Name>
  <Thickness>0.01</Thickness>
  <Material>S235</Material>
  <Origin>
    <Id>0</Id>
    <Name />
    <X>0.135</X>
    <Y>-0.06</Y>
    <Z>-0.36810000000000004</Z>
  </Origin>
  <AxisX>
    <X>0</X>
    <Y>-1</Y>
    <Z>0</Z>
  </AxisX>
  <AxisY>
    <X>-1</X>
    <Y>0</Y>
    <Z>-0</Z>
  </AxisY>
  <AxisZ>
    <X>0</X>
    <Y>-0</Y>
    <Z>-1</Z>
  </AxisZ>
  <Region>M 0 0.03 A 0.03 0.03 0 0 0 -0.03 0 A 0.03 0.03 0 0 0 0 -0.03 A 0.03 0.03 0 0 0 0.03 0 A 0.03 0.03 0 0 0 0 0.03</Region>
  <OriginalModelId>24</OriginalModelId>
  <IsNegativeObject>false</IsNegativeObject>
</PlateData>
```
In Idea Connection, plate looks like:

![image](https://user-images.githubusercontent.com/66376954/93460489-920fe000-f8e3-11ea-883d-c17adbb00054.png)

I have tried several options, but no success.

Could you please provide me the `svg` path commands to define a circular plate's region?

Best regards

**Comment by mpospisil** [comment]
we will prepare an example

**Comment by mpospisil** [comment]
There is the example of a ideacon project where you can find a circular baseplate. 

https://github.com/idea-statica/iom-examples/blob/release-20i/ConnCalcExamples/ConnectionHiddenCalculation/SingleTemplateTstProjects/circular-baseplate.ideaCon

you can upen it in our example and look at the geometry of the circular baseplate

![image](https://user-images.githubusercontent.com/19650653/96619564-9e35f580-1306-11eb-9b68-6c56bf1d1433.png)
