### ISSUE TITLE
[BUG] Wrong locations of angle cleats

### ISSUE THREAD

**Issue by jorgebslu** [idea-statica/iom-examples#41]
The locations of angle cleats are wrong in Idea Connection.
I am exporting to Idea Connection the attached [AngleCleats-047.zip](https://github.com/idea-statica/iom-examples/files/5256122/AngleCleats-047.zip) IOM and the location of both angle cleat is wrong in Idea Connection but looks fine in Idea.exe.

In Idea.exe:
![image](https://user-images.githubusercontent.com/66376954/93782082-6a45b280-fc2a-11ea-9ff9-bbb48242caf6.png)

In Idea Connection:

![image](https://user-images.githubusercontent.com/66376954/93782360-c577a500-fc2a-11ea-8db6-86c65d369d9e.png)

It also seems like the `Name` is ignored for both angle cleats.

 - OS: Windows 10 Pro-1909
 - IOM Version 20.0,104.57553
 - IdeaStatiCa Version  20.0,104.57553

I would appreciate any help on this topic.
Best regards

**Comment by mpospisil** [comment]
problem is that your IOM is not correct - we will try to prepare an example

**Comment by jorgebslu** [comment]
> problem is that your IOM is not correct - we will try to prepare an example

Any clue about what is wrong in iom please?
Idea.exe shows the angle cleats as expected :pensive:

**Comment by mpospisil** [comment]
Hi,

your IOM is not defined properly - look at the page :

https://github.com/idea-statica/ccm-examples

I've added an example how to connect a beam to a column. The most important thing is to pay the attention to the coordinate systems of members as well as to calculate right eccentricities. Look and compare it with your IOM.
