### ISSUE TITLE
[BUG] Cuts are wrong in BeamData

### ISSUE THREAD

**Issue by jorgebslu** [idea-statica/iom-examples#42]
Export the attached [iom99.zip](https://github.com/idea-statica/iom-examples/files/5259606/iom99.zip)  iom to Idea Connection.

Cuts applied on `Stiffening member 1` are wrong unless I am not understanding correctly how to apply cuts.
This is the connection I am exporting to Idea Connection:

![image](https://user-images.githubusercontent.com/66376954/93850693-e71a7000-fcae-11ea-9b55-ae6c547dbf5f.png)

And in Idea Connection I get:

* Without activating cuts on `BeamData `(just as starting point):
![image](https://user-images.githubusercontent.com/66376954/93850756-10d39700-fcaf-11ea-9fe5-6db6954417c6.png)

* Activating just `Cut 3`:
![image](https://user-images.githubusercontent.com/66376954/93852314-1c748d00-fcb2-11ea-8df1-c235d39a4ba0.png)
I tried to change dZ=-1 and there were no changes.

* With all cuts:
![image](https://user-images.githubusercontent.com/66376954/93850929-74f65b00-fcaf-11ea-8593-7745e1294c61.png)

What is not clear for me is the way that a cut plane is applied. I mean, what is the part of the object that is removed by the plane?
The one on the side of the normal vector, or the opposite side of the normal vector?
For example, in the following example, if I apply a cut plane to the yellow `BeamData`, what is the expected result, A or B?
I would expect A, that is, the removed portion is the one on the normal vector side.
![image](https://user-images.githubusercontent.com/66376954/93852856-16cb7700-fcb3-11ea-9b9d-e5ece801b345.png)

Best regards

 - OS: Windows 10 Pro-1909
 - IOM Version 20.0,104.57553
 - IdeaStatiCa Version 20.0,104.57553

**Comment by vojtech-chalupa** [comment]
Hello, 
this bug concerns cutting of stiffening members by workplanes. An improved method of cutting stiffening members will resolve this and is planned for the version 21 release.

**Comment by mpospisil** [comment]
fixed in version 21.0.0.2340

https://jurajsabatkaideastatica-my.sharepoint.com/:f:/g/personal/martin_pospisil_ideastatica_com/EnyVy8RZmedPghx0FcCwoP4BtmJpUuP0x9OTbpRiWP9o0A?e=fb3etS

![image](https://user-images.githubusercontent.com/19650653/112281918-df03b300-8c86-11eb-83b7-04ff3d93cf5a.png)
