### ISSUE TITLE
Multiple Connections from IOM in one project

### ISSUE THREAD

**Issue by NathanlGG** [idea-statica/iom-examples#43]
Hi, 
I am wanting to generate multiple connections in one IdeaStatica project. I have defined two connections in the below OpenModel attached. It generates the IDEAStatica Connection File no problems although only the first set of connection data is available. 

Is there something I am missing to enable multiple connections or is there something additional I need to set?  

Any help appreciated.

`  <ConnectionPoint>
    <ConnectionPoint>
      <Id>1</Id>
      <Name>CON 1</Name>
      <Node>
        <TypeName>Point3D</TypeName>
        <Id>2</Id>
      </Node>
      <ConnectedMembers>
        <ConnectedMember>
          <Id>3</Id>
          <MemberId>
            <TypeName>Member1D</TypeName>
            <Id>3</Id>
          </MemberId>
          <IsContinuous>true</IsContinuous>
          <OriginalModelId>3</OriginalModelId>
          <Length>0</Length>
        </ConnectedMember>
        <ConnectedMember>
          <Id>1</Id>
          <MemberId>
            <TypeName>Member1D</TypeName>
            <Id>1</Id>
          </MemberId>
          <IsContinuous>false</IsContinuous>
          <OriginalModelId>1</OriginalModelId>
          <Length>0</Length>
        </ConnectedMember>
      </ConnectedMembers>
      <NodeId>2</NodeId>
      <ProjectFileName>connectionFromIOM-local.ideaCon</ProjectFileName>
    </ConnectionPoint>
    <ConnectionPoint>
      <Id>2</Id>
      <Name>CON 2</Name>
      <Node>
        <TypeName>Point3D</TypeName>
        <Id>8</Id>
      </Node>
      <ConnectedMembers>
        <ConnectedMember>
          <Id>4</Id>
          <MemberId>
            <TypeName>Member1D</TypeName>
            <Id>4</Id>
          </MemberId>
          <IsContinuous>false</IsContinuous>
          <OriginalModelId>4</OriginalModelId>
          <Length>0</Length>
        </ConnectedMember>
        <ConnectedMember>
          <Id>6</Id>
          <MemberId>
            <TypeName>Member1D</TypeName>
            <Id>6</Id>
          </MemberId>
          <IsContinuous>true</IsContinuous>
          <OriginalModelId>6</OriginalModelId>
          <Length>0</Length>
        </ConnectedMember>
      </ConnectedMembers>
      <NodeId>8</NodeId>
      <ProjectFileName>connectionFromIOM-local.ideaCon</ProjectFileName>
    </ConnectionPoint>
  </ConnectionPoint>
  <Connections>
    <ConnectionData>
      <Beams>
        <BeamData>
          <Id>3</Id>
          <Name>M3</Name>
          <OriginalModelId>3</OriginalModelId>
          <IsAdded>false</IsAdded>
          <IsNegativeObject>false</IsNegativeObject>
          <MirrorY>false</MirrorY>
          <RefLineInCenterOfGravity>false</RefLineInCenterOfGravity>
          <IsBearingMember>true</IsBearingMember>
          <AutoAddCutByWorkplane>false</AutoAddCutByWorkplane>
        </BeamData>
        <BeamData>
          <Id>1</Id>
          <Name>M1</Name>
          <OriginalModelId>1</OriginalModelId>
          <IsAdded>false</IsAdded>
          <IsNegativeObject>false</IsNegativeObject>
          <MirrorY>false</MirrorY>
          <RefLineInCenterOfGravity>false</RefLineInCenterOfGravity>
          <IsBearingMember>false</IsBearingMember>
          <AutoAddCutByWorkplane>false</AutoAddCutByWorkplane>
        </BeamData>
      </Beams>
    </ConnectionData>
    <ConnectionData>
      <Beams>
        <BeamData>
          <Id>4</Id>
          <Name>M4</Name>
          <OriginalModelId>4</OriginalModelId>
          <IsAdded>false</IsAdded>
          <IsNegativeObject>false</IsNegativeObject>
          <MirrorY>false</MirrorY>
          <RefLineInCenterOfGravity>false</RefLineInCenterOfGravity>
          <IsBearingMember>true</IsBearingMember>
          <AutoAddCutByWorkplane>false</AutoAddCutByWorkplane>
        </BeamData>
        <BeamData>
          <Id>6</Id>
          <Name>M6</Name>
          <OriginalModelId>6</OriginalModelId>
          <IsAdded>false</IsAdded>
          <IsNegativeObject>false</IsNegativeObject>
          <MirrorY>false</MirrorY>
          <RefLineInCenterOfGravity>false</RefLineInCenterOfGravity>
          <IsBearingMember>false</IsBearingMember>
          <AutoAddCutByWorkplane>false</AutoAddCutByWorkplane>
        </BeamData>
      </Beams>
    </ConnectionData>
  </Connections>`

**Comment by mpospisil** [comment]
Hi Nathan

I suppose it should be possible but in our new CCM we support only one connection in idea connection project. If you want your application to be compatible with CCM and Idea Member which allows to do buckling check of all member do not use more connections in the project.

Look at : 
https://github.com/idea-statica/ccm-examples

if you still prefere to have more connections attach your IOM file

**Comment by NathanlGG** [comment]
Thanks Martin.

I think it would be great to be able to set-up multiple connections in one file. I have provided the IOM. 

[exampleIOMMultipleConnections.zip](https://github.com/idea-statica/iom-examples/files/5279734/exampleIOMMultipleConnections.zip)

**Comment by jorgebslu** [comment]
> I think it would be great to be able to set-up multiple connections in one file. I have provided the IOM.

:+1:  That is something that we also need.

**Comment by mpospisil** [comment]
Hi,
our recommended way is CCM. Let's focus on this way, I know it is not perfect but I prefere to improve this way. We provide automatic features for updating geometry as well as loading.

I know the users interaction is needed but if you send us your use case we can add it to our development backlog.
