### ISSUE TITLE
[BUG] Unable to export beam notches to Idea Connection

### ISSUE THREAD

**Issue by jorgebslu** [idea-statica/iom-examples#45]
Hi,

I am trying to export a couple of beam notches (with a rounding corners) to Idea Connection like the following:

![image](https://user-images.githubusercontent.com/66376954/93989236-f28e9980-fd89-11ea-829c-583984b73d9f.png)

* I have tried to create both notches by using `BeamData` objects [NotchesAsBeamData-iom.zip](https://github.com/idea-statica/iom-examples/files/5266875/NotchesAsBeamData-iom.zip), but it failed.
FYI, in Idea.exe, both members look like:

![image](https://user-images.githubusercontent.com/66376954/93989996-df2ffe00-fd8a-11ea-821c-ee90ff25b362.png)

I needed to define `Material` property for the `CssComponent` to prevent failure. It is weird because the material is not needed because the section will be used by a member that behaves as a cutting solid.

* I also tried to create both notches by using `PlateData` objects [NotchesAsPlateData-iom.zip](https://github.com/idea-statica/iom-examples/files/5266881/NotchesAsPlateData-iom.zip) and it also failed.

I guess that the issue could be related to the fact that I am not setting `Material` to `PlateData` & `IsNegativeObject = true`, which shouldn't be a problem for a cutting volume.
In case I set up `Material` and don't consider as cutting object (`IsNegativeObject = false`), Idea Connection fails and shows some message I cannot read:

![image](https://user-images.githubusercontent.com/66376954/93995902-dee73100-fd91-11ea-9f68-90b645df6f98.png)

Could you please let me know how to define notches in IOM?

Best regards

- OS: Windows 10 Pro-1909
- IOM Version 20.0,104.57553
- IdeaStatiCa Version 20.0,104.57553

Edited:
I have exported a connection from Tekla Structures to Idea Connection and I see that notch is defined as a member:
![image](https://user-images.githubusercontent.com/66376954/94008155-cf241880-fda2-11ea-8290-31a53bedce65.png)
So, if member is used, which properties should be used for it?

**Comment by vojtech-chalupa** [comment]
Hello, this issue is now resolved, starting from version 21, the material won't be required for a negative volume cross-section.
