### ISSUE TITLE
[BUG] Missing welds to Idea Connection

### ISSUE THREAD

**Issue by jorgebslu** [idea-statica/iom-examples#46]
Hi,
I am trying to export the attached iom [webPlate-iom.zip](https://github.com/idea-statica/iom-examples/files/5275171/webPlate-iom.zip) to Idea Connection and some welds are missing:

![image](https://user-images.githubusercontent.com/66376954/94132542-baf22100-fe5f-11ea-9cad-5624ddd11314.png)

![image](https://user-images.githubusercontent.com/66376954/94133661-3d2f1500-fe61-11ea-9a2f-5b6b66c135a8.png)

FYI: to try to figure it out if I was doing something wrong, I also exported a similar connection from Tekla Structures to Idea Connection, and some weird welds were exported:

* Tekla Structures:
![image](https://user-images.githubusercontent.com/66376954/94132893-394ec300-fe60-11ea-9878-ee7e68ca7acd.png)

* [Idea Connection:](https://github.com/idea-statica/iom-examples/files/5275212/Conn-2.zip)
![image](https://user-images.githubusercontent.com/66376954/94133037-67340780-fe60-11ea-966b-104367982e99.png)

Could you please take a look at this issue?

Best regards

- OS: Windows 10 Pro-1909
- IOM Version 20.0,104.57553
- IdeaStatiCa Version 20.0,104.57553

**Comment by mpospisil** [comment]
adding bug to DevOps and assigned to David Jaros

**Comment by mpospisil** [comment]
There are several issues in your model : 
* use **double fillet weld** instead of two welds - we do not allow two same welds
* start/end point  both points should be equal and they should by located in the middle of the connected edge. I know it is confusing - it is our mistake.

When you change your model it should be fine
