### ISSUE TITLE
[BUG] Welds/Boltgrids missing from ConnectionData

### ISSUE THREAD

**Issue by Basnederveen** [idea-statica/iom-examples#47]
When extracting the ConnectionData from a connection I've encountered that there are BoltGrids in the IDEA connection, but not in the output data. It seems quite random, in IDEA the connection looks fine, but once the geometry is extracted and parsed to JSON, some items are gone.

For the boltgrids:
Connection:
![image](https://user-images.githubusercontent.com/16050771/94254890-b2fdb400-ff27-11ea-8100-7feddbdafa51.png)

JSON Output:
![image](https://user-images.githubusercontent.com/16050771/94254968-d294dc80-ff27-11ea-9d48-f3c7e2104766.png)

For the welds:
Connection:
![image](https://user-images.githubusercontent.com/16050771/94255157-17b90e80-ff28-11ea-8e1d-f4013dffcd98.png)

JSON Output:
![image](https://user-images.githubusercontent.com/16050771/94255110-07089880-ff28-11ea-9539-8bcc0f2893ac.png)

Info:
 - OS: Windows 10
 - IdeaStatiCa Version 20.0

**Comment by vojtech-chalupa** [comment]
Hello, this has now been resolved. The output from version 20.1.4367.1 produces a complete set of data.
