### ISSUE TITLE
[QUESTION] Material & Standard for BoltGrid object

### ISSUE THREAD

**Issue by jorgebslu** [idea-statica/iom-examples#48]
Hi,

`OpenModel` object has container lists for `MatSteel`, `MatConcrete`, `MatPrestressSteel`, `MatReinforcement` but it does not have a property like `List<MaterialBoltGrade>`.

![image](https://user-images.githubusercontent.com/66376954/94260623-ceb98800-ff30-11ea-82e8-8e83acf5d4e3.png)

`Material` class: https://idea-statica.github.io/iom/iom-api/latest/html/T_IdeaRS_OpenModel_Material_Material.htm

I need to create an instance of `BoltGrid` and a [Material](https://idea-statica.github.io/iom/iom-api/latest/html/P_IdeaRS_OpenModel_Connection_BoltGrid_Material.htm) property is required.
The help documentation says _The material of the bolt assembly_ .

If I cannot add to `OpenModel` an instance of `MaterialBoltGrade`, what is the value I have to provide to the `BoltGrid.Material` property ?

The example at [SteelFrameExample.cs](https://github.com/idea-statica/iom-examples/blob/master/IOM_SteelFrame1/IOM.GeneratorExample/SteelFrameExample.cs) provides "8.8" but it is not clear for a complex example to determine it from a user defined bolt assembly.

I would also appreciate further help on `BoltGrid.Standard` property. Concerning the relation of that property with the properties of `OpenModel `.

Best regards

* OS: Windows 10 Pro-1909
* IOM Version 20.0,104.57553
* IdeaStatiCa Version 20.0,104.57553

**Comment by mpospisil** [comment]
Pavel will send you an answer for your question

**Comment by mpospisil** [comment]
IOM model was originally intended for import the model from FEA applications - there are no bolts. If you want to get a list of bolt assemblies or add a new one - you can use methods

GetBoltAssembliesInProject
AddBoltAssembly

see the example :

https://idea-statica.github.io/iom-examples/iom-steel-connections/cbfem-for-all.html

on the other hand you can import structures from CAD applications where users can define geometries of connections see

https://github.com/idea-statica/ccm-examples

https://github.com/idea-statica/ccm-examples/blob/release-v20.1/FEAppExample_1/CAD_Model_Examples/Column-On-BasePlate.xml

or

https://github.com/idea-statica/ccm-examples/blob/release-v20.1/FEAppExample_1/CAD_Model_Examples/Column-CHS-EndPlates.xml

they show how to import FEA model as well as connections
