### ISSUE TITLE
[BUG] There are no Washer properties in BoltGrid

### ISSUE THREAD

**Issue by jorgebslu** [idea-statica/iom-examples#49]
Hi,

The [BoltGrid](https://idea-statica.github.io/iom/iom-api/latest/html/T_IdeaRS_OpenModel_Connection_BoltGrid.htm) object has a property for Nut, which is named [NutThickness](https://idea-statica.github.io/iom/iom-api/latest/html/P_IdeaRS_OpenModel_Connection_BoltGrid_NutThickness.htm) but there are no properties for washers, for example:

```csharp
public double WasherThickness { get; set; }
public bool WasherAtHead { get; set; }
public bool WasherAtNut { get; set; }
```

As these are missing properties, I cannot understand where the following values for washer are coming from?

![image](https://user-images.githubusercontent.com/66376954/94408277-d9fcf580-0174-11eb-8248-92bcfd7613ca.png)

It seems like IdeaConnection is using WasherThickness = 0.2 * NutThickness.

Could it be possible to add the missing properties for washers ?

Best regards

* OS: Windows 10 Pro-1909
* IOM Version 20.0,104.57553
* IdeaStatiCa Version 20.0,104.57553

[webPlate+endPlate-iom.zip](https://github.com/idea-statica/iom-examples/files/5290905/webPlate%2BendPlate-iom.zip)

**Comment by mpospisil** [comment]
We will add it to development
