### ISSUE TITLE
Retrieve LCS of LinseSegment3D

### ISSUE THREAD

**Issue by BouwenmetStaal** [idea-statica/iom-examples#5]
I want to make a plate that is orientated based on the local coordinate system (LCS) of the attached beam.

In order to do so, I want to retrieve the LCS-vectors of the beam and implement them in the LCS of the plate. However, in the Class CoordSystem, the properties cannot be retrieved:

`CoordSystem coor = openModel.LineSegment3D[refBeam].LocalCoordinateSystem;`
https://idea-statica.github.io/iom/iom-api/latest/html/25041a51-98ad-91db-c8b9-a13c9d3637a9.htm

How can I retrieve the LCS of a LineSegment3D?

**Comment by mpospisil** [comment]
You need to create LCS for plates manually - it is the transformation matrix. You can not read it from LineSegment3D

**Comment by BouwenmetStaal** [comment]
Unfortunately,

It might be something to include in the next version?

It would be very useful.

**Comment by mpospisil** [comment]
We have published IdeaStatiCa.PluginsTools (it is BETA now, it will be released in November)

https://github.com/idea-statica/ideastatica-plugin/tree/idea-statica-v20i

You will find the class

**CI.Geometry3D.Matrix44**

which includes methods 

CI.Geometry3D.Matrix44.TransformToGCS / CI.Geometry3D.Matrix44.TransformToLCS

it heps to transform LCS <-> GCS
