### ISSUE TITLE
[BUG] Column shorter than expected

### ISSUE THREAD

**Issue by jorgebslu** [idea-statica/iom-examples#51]
Hi,
I need to export the [attached](https://github.com/idea-statica/iom-examples/files/5328704/BME016-20-IOM.zip) iom to `Idea Connection` and the column appears shorter than expected:

* In `Idea.exe`, column has the correct height:

![image](https://user-images.githubusercontent.com/66376954/95106477-dd761b00-0738-11eb-9b3f-1c3f4746491f.png)

* In `Idea Connection`, column is shorter than it should be:

![image](https://user-images.githubusercontent.com/66376954/95106623-072f4200-0739-11eb-908f-f4e1b4b8a6f8.png)

FYI: there are not cut operations applied to the column.

* OS: Windows 10 Pro-1909
* IOM Version 20.0,104.57553
* IdeaStatiCa Version 20.0,104.57553

**Comment by mpospisil** [comment]
The first operation should be the workplane, the second one but beam by beam which extend a the beam to the required position. Same as you do applicatio.

**Comment by jorgebslu** [comment]
There is no workplane nor cut beam-by-beam. The column end point is just as defined, no operation are required/performed.
The 2 workplanes you see are cut planes for both beams (horizontal members).
I beg you to take a look at this issue please.

**Comment by mpospisil** [comment]
There is - look at the example

https://github.com/idea-statica/ccm-examples/blob/release-v20.1/FEAppExample_1/CAD_Model_Examples/Column-On-BasePlate.xml

the first and the secon operation

**Comment by jorgebslu** [comment]
In your example you have defined operations, but not in my example because they are not needed.
Operations are not mandatory to set up the start and end position of a member.

**Comment by mpospisil** [comment]
The example this was generated by our link from Tekla Structures. Some operations can be omitted but in your example will solve your problem. I will look at your IOM later.

**Comment by mpospisil** [comment]
Look at the analysis model - there is one point where mebers are connected. The rest are operations - you need to extend the column to the top edge of the beam and cut beam by the column

![Starting-point](https://user-images.githubusercontent.com/19650653/95906158-0d0ccf00-0d9a-11eb-88d3-b4a8205bc389.PNG)

**Comment by jorgebslu** [comment]
Hi again.
My example is:
![image](https://user-images.githubusercontent.com/66376954/95971905-13d72880-0e12-11eb-970b-8a7e2397462e.png)

Column goes from Id=1 to Id=2.
Beam goes from Id=3 to Id=4.
So, column has the correct height as Idea.exe is showing and confirming.

It is extremely annoying to put the focus where the connection point is defined, because it destroys the definition of the members. It requires a post processing of the members according to the location of the connection point.
Indeed, connection point is something that is not actually needed for the definition of a connection.
The following example is also an exportation from TS 2020 to Idea by using your plugin:

![image](https://user-images.githubusercontent.com/66376954/95972328-9b249c00-0e12-11eb-8916-04130a494648.png)

As you can see, the resulting height of the column does not look equal than Tekla Structures.

From the very beginning, I had the impression that IOM was an invariant definition of a model, so according to your answer, IOM data depends on the destination application (in this case, Idea Connection) becase some extra operations are required to obtain the expected connection's geometry.

Please, keep in mind that our plugin converts 3D models with connections to Idea Connection by considering the provided geometry from our users, so according to your answer, we should post-process the IOM to see whether or not some extra operations are required to fit the Idea Connection rules.

BTW, if I define the connection point in an arbitrary [3D location](https://github.com/idea-statica/iom-examples/files/5377347/Conn-1.zip) (from Tekla Strucrtures to Idea), this is what I get in Idea Connection:

![image](https://user-images.githubusercontent.com/66376954/95974478-53534400-0e15-11eb-9105-2c6c6cc95815.png)

As you can see, the work plane at the column base is weird at all.
