### ISSUE TITLE
[QUESTION] Adding Loads into the Connection Model 

### ISSUE THREAD

**Issue by EricDuongED** [idea-statica/iom-examples#52]
I'm relatively new to programming and I was wondering if there's an easier way to manually input loads to the IOM besides creating an XML file with the specified format outlined here?

https://idea-statica.github.io/iom-examples/iom-steel-connections/steel-frame1.html

If there isn't can you point me in the right direction on how to serialize an XML file with that specific format?

**Comment by mpospisil** [comment]
Hi Eric, look at

https://idea-statica.github.io/iom/iom-api/latest/html/T_IdeaRS_OpenModel_Result_OpenModelResult.htm

You can create an instance of this class (including correct internal forces) then you can use the method SaveToXmlFile). The implementation can be found here 

https://github.com/idea-statica/iom/blob/master/IdeaRS.OpenModel/OpenModelResult.cs
