### ISSUE TITLE
[QUESTION] Is it possible to use the templates from IDEA StatiCa Connection?

### ISSUE THREAD

**Issue by EricDuongED** [idea-statica/iom-examples#53]
Is it possible to build your model in IOM through one of the templates given in IDEA StatiCa Connection or do you have to build every connection from scratch and use that code as a template?
![image](https://user-images.githubusercontent.com/72173783/95545787-1540c500-09bc-11eb-897b-13873199a33d.png)

**Comment by mpospisil** [comment]
It is not, but you can craete your templates and use them - see the document

https://idea-statica.github.io/iom-examples/iom-steel-connections/cbfem-for-all.html

there is a brief description how to create and apply templates
