### ISSUE TITLE
[QUESTION]Is it possible to specify weld thickness when using CutBeamByBeamData?

### ISSUE THREAD

**Issue by EricDuongED** [idea-statica/iom-examples#54]
Not sure if these following questions have been asked before but:

1) Is it possible to specify the weld thickness when you are using the CutBeamByBeamData class?

2) When I specify false for the IsWeld property of the CutBeamByBeamData the weld still shows up. Is there a way to get around this?

**Comment by vadura-pavel** [comment]
Hello Eric,
1.	Now CutBeamByBeamData doesn’t offer possibility set specific weld properties. Anyway we put the request to a list of new features.
2.	Property IsWeld should works. Can you attach your IOM model?

**Comment by mpospisil** [comment]
If the property "WELD SIZE" is set to 0 - the value is takes from the connected thinner plate

**Comment by mpospisil** [comment]
Hi Eric,
can we close this issue ?

**Comment by EricDuongED** [comment]
Hi Martin, 

The issue when specifying IsWeld to false is still prevalent. When I use CutBeamByBeam and specify the IsWeld to false, the weld ends up being a single fillet weld and the thickness is the minimum plate thickness of the connecting members.

**Comment by mpospisil** [comment]
in version 21.0 Beta 
the class CutBeamByBeamData ( https://github.com/idea-statica/iom/blob/release-21.0.0-beta/IdeaRS.OpenModel/Connection/ConnectionData.cs ) has the property

		/// <summary>
		/// Type of the weld
		/// </summary>
		public WeldType WeldType { get; set; }

if you set it to NotSpecified weld is not created
