### ISSUE TITLE
[BUG]Incorrect welds

### ISSUE THREAD

**Issue by dataneodev** [idea-statica/iom-examples#56]
Hi.

I noticed that the new version is importing welds incorrectly.

![image](https://user-images.githubusercontent.com/38402428/97534978-309b6080-19bb-11eb-9845-08b47e9324f9.png)

![image](https://user-images.githubusercontent.com/38402428/97535067-558fd380-19bb-11eb-9849-f38324e68c64.png)

OpenModel for this connection : [OpenModel.zip](https://github.com/idea-statica/iom-examples/files/5456613/OpenModel.zip)

 - OS:  Windows 10
 - IOM Version 20.0.8, 20.1
 - IdeaStatiCa Version 20.0.104 / 20.1.2515

**Comment by mpospisil** [comment]
Hi 
I would say problem is in your model - an edge - surface weld must be unique in your model and I expect we are finding more welds in the same position.

We improved the detection of welds in v20.1 -  we can detect welds which were omitted in v20.0

**Comment by dataneodev** [comment]
In open model welds are defined by 2 points.

In the file above, the weld "Weld_Plate_12_Plate_01_01" and "Weld_Plate_12_Plate_02_02" are not in the same place.
They are shifted by Y: 27mm - plate 25mm + 1mm offset on both sides.

You can provide additional explanations?

```

<WeldData>
          <Id>30028</Id>
          <Name>Weld_Plate_12_Plate_01_01</Name>
          <Thickness>0.012</Thickness>
          <Material>S355_T16_40</Material>
          <WeldType>DoubleFillet</WeldType>
          <ConnectedPartIds>
            <string>20012</string>
            <string>20001</string>
          </ConnectedPartIds>
          <Start>
            <Id>0</Id>
            <X>0.73903313488654687</X>
            <Y>-0.013750000000000172</Y>
            <Z>-0.66573163731419971</Z>
          </Start>
          <End>
            <Id>0</Id>
            <X>0.40500428981673781</X>
            <Y>-0.013750000000000007</Y>
            <Z>-0.22581564835726123</Z>
          </End>
        </WeldData>
        <WeldData>
          <Id>30029</Id>
          <Name>Weld_Plate_12_Plate_02_02</Name>
          <Thickness>0.012</Thickness>
          <Material>S355_T16_40</Material>
          <WeldType>DoubleFillet</WeldType>
          <ConnectedPartIds>
            <string>20012</string>
            <string>20001</string>
          </ConnectedPartIds>
          <Start>
            <Id>0</Id>
            <X>0.38270424602153297</X>
            <Y>0.013249999999999996</Y>
            <Z>-0.24274810378262554</Z>
          </Start>
          <End>
            <Id>0</Id>
            <X>0.7167330910913422</X>
            <Y>0.013249999999999819</Y>
            <Z>-0.682664092739564</Z>
          </End>
        </WeldData>
```
![obraz](https://user-images.githubusercontent.com/38402428/97622850-2150fd00-1a25-11eb-96a2-047866c8f578.png)

**Comment by mpospisil** [comment]
As I mentioned - start/end points of welds are confusing. Add two welds and
set their positions according to your picture - points should be in the
middle of the welded edges.
It should work - see the attach project.

Martin
