### ISSUE TITLE
[QUESTION]Material Class - LoadFromLibrary 

### ISSUE THREAD

**Issue by EricDuongED** [idea-statica/iom-examples#57]
When we specify the property LoadFromLibrary to true for a certain material, how do we specify which material we want to load from IDEA StatiCa? 

I've tried naming the material as a string, i.e., "300W" for a MatSteelCISC class; however, the output file always gives me A36

**Comment by mpospisil** [comment]
can you provide me a snippet of your code where you define your material

**Comment by EricDuongED** [comment]
The current string for the the beam/column/plate grades is "350W".
![image](https://user-images.githubusercontent.com/72173783/97919972-ee08b980-1d15-11eb-8b6b-9a935eb31732.png)

And then once the material is generated in the model, I pass "350W" into this method to create the cross section
![image](https://user-images.githubusercontent.com/72173783/97920133-3b852680-1d16-11eb-96de-130afbd83ddc.png)

**Comment by mpospisil** [comment]
Do you have the correct setting of the design code for your project ?  I mean if you open your generated project in ideaconnection.exe - what is the design code for the project ?

**Comment by EricDuongED** [comment]
Design code should bet set to the Canadian code, when I open up the project, it shows CISC which should be correct.

![image](https://user-images.githubusercontent.com/72173783/97931900-e8b66980-1d2b-11eb-8d1c-5bb0b766e874.png)

**Comment by mpospisil** [comment]
Hi Eric,

You have found the bug - it will be fixed in the next pathch (IS 20.1.2). Your code seems to be fine. 

Martin

**Comment by mpospisil** [comment]
adding bug #2485 to DevOps

**Comment by mpospisil** [comment]
fixed in version 21.0.0.2340 

https://jurajsabatkaideastatica-my.sharepoint.com/:f:/g/personal/martin_pospisil_ideastatica_com/EnyVy8RZmedPghx0FcCwoP4BtmJpUuP0x9OTbpRiWP9o0A?e=fb3etS
