### ISSUE TITLE
[QUESTION] Potential CutBeamByBeam bug and WeldData question

### ISSUE THREAD

**Issue by EricDuongED** [idea-statica/iom-examples#58]
Two things. Firstly, I believe that the functionality of CutBeamByBeam is not working as intended. If a beam is cut by a plate that is connected to a column, the area that is not cut by the plate is still connected to the column even though it doesn't visually look that way. This can be shown below, the area of the beam that is highlighted in red is connected to the end plate but the area in blue is connected to the column.

The beam was generated using CutBeamByBeam and within the model. It looks as if the beam is only connected to the end plate by a weld. However, when we run the analysis, the results are not what one would expect especially when the members (WWF700x152 column & W410x46 beam) are only subjected to a 100KN shear force. As we can see from the stress analysis, the majority of the stress is at the top flange of the beam which doesn't make sense which leads me to believe that the top part of the beam (not connected to the end plate) is actually connected to the column.

![image](https://user-images.githubusercontent.com/72173783/98655417-ab8a4280-22fc-11eb-9047-d0be4a958574.png)
![image](https://user-images.githubusercontent.com/72173783/98652896-88aa5f00-22f9-11eb-8f9a-71d460db3f31.png)
![image](https://user-images.githubusercontent.com/72173783/98653463-4cc3c980-22fa-11eb-913d-258dd3b72e21.png)

When I change the connection point of the beam and column to the location of the end plate and then use CutBeamByBeam, the results produced are as shown (seems a lot more reasonable). By doing this, the beam is never in contact with the column thus creating the intended analysis results with the end plate. 

![image](https://user-images.githubusercontent.com/72173783/98653852-c78ce480-22fa-11eb-971d-0bdc3204e273.png)

I'm not sure if this has been previously reported but I figure that this is not the intention of CutBeamByBeam and wanted to bring the issue to light. 

The second thing includes two questions regarding the WeldData class. Firstly, when I specify the material for the weld (i.e., "E49xx"), the model still produces a weld with E70xx. Is there a different way to specify the weld material?

Secondly, for some reason, the thickness of the weld is always a 1.414 factor larger than the weld that I specify. For example, when I specify a 10mm weld it shows a 14.14mm weld in the model. 

Here's a snippet of the code for an end plate connection that specifies the weld that produces this problem:
![image](https://user-images.githubusercontent.com/72173783/98654486-9e208880-22fb-11eb-9b60-1e2f1622fb79.png)
![image](https://user-images.githubusercontent.com/72173783/98654511-a5e02d00-22fb-11eb-86e8-df3adc3e806a.png)
![image](https://user-images.githubusercontent.com/72173783/98654843-0b341e00-22fc-11eb-88d2-3f27985522b1.png)

Image of model when I specify a 5mm thickness weld (5x1.414 =7.07):
![image](https://user-images.githubusercontent.com/72173783/98655053-46365180-22fc-11eb-9b4b-0f5905f5a8f8.png)

**Comment by mpospisil** [comment]
Hi Eric,

can you attach your generated idea connection project file and your IOM (xml). We will look at it. I believe it is the problem in your model. The implementation is same as it is in our desktop application.

**Comment by EricDuongED** [comment]
Hey Martin, 

Here's the idea connection project file and xml, it's slightly different from the one shown in the pictures as I accidently deleted that file and have since changed my code.

[End_Plate.zip](https://github.com/idea-statica/iom-examples/files/5580080/End_Plate.zip)

**Comment by vojtech-chalupa** [comment]
Eric, thank you for the files, Martin or Pavel will review them. We will also investigate the weld material issue and let you know.
As for the weld sizes, the IOM works strictly with the fillet weld "throat" size. 
In the app, it is presented as "throat" or "leg" size, depending on the Code used. "Leg" size is the "throat" size multiplied by SQRT(2).

**Comment by vojtech-chalupa** [comment]
Looking at the model you provided - geometrically, it seems fine. But what you also need to consider is the shear load position. Here is a relevant support center article:
https://www.ideastatica.com/support-center/how-to-define-correct-load-position

By changing the connection point, you've effectively moved the load position. In the Connection app, select a load case and activate the "wireframe" view. You will then see a bending moment diagram. Depending on the load position, there might be an additional bending moment acting on the endplate:

![image](https://user-images.githubusercontent.com/73105487/100750876-ead11e00-33e6-11eb-8f10-c266490521cc.png)

**Comment by vojtech-chalupa** [comment]
Closing this question, it is considered to be resolved. Feel free to reopen.
