### ISSUE TITLE
Classes are limited

### ISSUE THREAD

**Issue by GRamsaroep** [idea-statica/iom-examples#6]
Hi,

Some calsses, like CutBeamByBeamData, are limited with input of information or am i wrong? Because in IDEA i can give the lengths of the welds for the cutbeam operation but in the IOM there are only 3 parameters that can be changed, the CuttingObject, ModifiedObject and IsWeld. In the november patch, are there gonna be more input possibilities?

**Comment by mpospisil** [comment]
You are right - possibilities are  limited now. This API has been developed mainly from import of connections from CAD applications (e.g. Tekla, AS, Revit)
In the future we would like to have chance how to define a manufacturing sequence of a connection (same as you can define in ideaconnection)

**Comment by GRamsaroep** [comment]
Hi Martin,

Where is the sample project that you have uploaded on github? I am going to
try and use this new update and see if i can get all the info out of an
project.

Regards,

Giorgio

Op vr 25 okt. 2019 om 12:06 schreef Martin Pospisil <
notifications@github.com>:

**Comment by GRamsaroep** [comment]
Dear Martin,

I can't open the exe file. It keeps giving me the error NoApiBlyb or
something. I tried to run as admin and then it keeps saying there is no
license found.

Regards,

GIorgio

Op vr 25 okt. 2019 om 12:06 schreef Martin Pospisil <
notifications@github.com>:

**Comment by mpospisil** [comment]
Can you provide me more information about your problem - how do you call it, is Idea StatiCa installed correctly on your PC ? Which version ?

**Comment by GRamsaroep** [comment]
I use version 10.1 on my PC and also have version 9 installed. The problem
is that it doesn't recognised my license on the server. I want to test the
API files to get info out of the projects of IDEA. We at Voortman want to
make a link back to Tekla for the connections. If you have more questions
or info needed, i will provide you the info. Tomorrow i can test the
license back at the office on the server. RIght now im working at home.

Regards,

Giorgio

Op wo 4 dec. 2019 om 13:28 schreef Martin Pospisil <notifications@github.com

**Comment by mpospisil** [comment]
Please test it in the office and let us know

**Comment by GRamsaroep** [comment]
Hi Martin,

I am testing it now in the office, but it gives me still the error message.
Both IDEA 10 and 9 are working fine, but the exe form the zip file doesnt
work. Gives me the same error as yesterday : NoAPIDyLib. How can i fix this
problem?

Regards,

Giorgio

Op wo 4 dec. 2019 om 13:56 schreef Martin Pospisil <notifications@github.com

**Comment by mpospisil** [comment]
It seems native dlls for hasp are not loaded. Lets try to copy all your assemblies into the Idea StatiCa installation directory and run it from this location.

You can send me your email and we can plan a web meeting.

**Comment by GRamsaroep** [comment]
Hi Martin,

These upcoming week i have other work that has the priority at the moment.
Is it oke to schedule a meeting next week  on friday the 13th maybe or the
week after next week (week of monday 16th)?

I want to make the steps to read the info out of a project from IDEA so i
can make the link to Tekla.

My work email is g.ramsaroep@vsc.nl

Regards,

Giorgio Ramsaroep

Op do 5 dec. 2019 om 09:48 schreef Martin Pospisil <notifications@github.com

**Comment by GRamsaroep** [comment]
Goodmorning Martin,

Is it possible to do a online meeting on monday, tuesday or wednesday next
week? There was a change of plans in the schedule. I am available the
upcoming week on monday, tuesday and wednesday.

Hope this suits your schedule.

Regards,

Giorgio Ramsaroep

Op do 5 dec. 2019 om 15:05 schreef Giorgio Ramsaroep <
sgiorgioramsaroep@gmail.com>:

**Comment by mpospisil** [comment]
Hi Giorgio,

can we have our meeting on wednesday Novemeber 11th - let's say at 10am CET

Regards,
Martin

**Comment by GRamsaroep** [comment]
Hi Martin,

That would be great! 10 AM CET wednesday.

Regards,

GIorgio

Op ma 9 dec. 2019 om 09:50 schreef Martin Pospisil <notifications@github.com
