### ISSUE TITLE
[BUG] Consteel to Idea 20.1 failed

### ISSUE THREAD

**Issue by vtorok** [idea-statica/iom-examples#61]
Hi,
It has been noticed that something has been changed in Idea between ver 20 and 20.1 regarding the export from Consteel to Idea. Consteel uses an XML file to export the parts of a connection to IDEA. It worked well in ver. 20 but in ver. 20.1 the signs of the exported forces are interchanged. The forces in ver. 20.1 are therefore not in equilibrium, too. See the attached pictures and files.

What has been modified in this field in IDEA since version 20?
Was it needed or is it a bug maybe?

XML file and screenshots are attached.

[2039-E61.csm - IDEA IOM.zip](https://github.com/idea-statica/iom-examples/files/5607810/2039-E61.csm.-.IDEA.IOM.zip)
![Exported model to ver20](https://user-images.githubusercontent.com/75124590/100449330-015c3a00-30b4-11eb-8261-dd9c70812afc.jpg)
![Exported model to ver20-1](https://user-images.githubusercontent.com/75124590/100449340-0620ee00-30b4-11eb-8d8b-9219619f13ba.jpg)

Best regards,
Vazul Török
Consteel Solutions Ltd.

**Comment by mpospisil** [comment]
In the newer version we respect the local coordinate system of members from the original model. Check coordiante systems in your model, imported connections - they should be same. That is why the end and the begin are swapped

**Comment by vojtech-chalupa** [comment]
Hello, the bug has now been solved. The fix will be a part of the next patch coming this week.
