### ISSUE TITLE
[BUG]Weld export problem.

### ISSUE THREAD

**Issue by dataneodev** [idea-statica/iom-examples#62]
Hi.

In the latest version 20.1.3471.1 there is still a problem with exporting welds.
Please take a look at attachment.

1.
![1_mta](https://user-images.githubusercontent.com/38402428/101181186-e0b05900-364c-11eb-9d5e-d57ed6ebe6af.PNG)
![1_idea](https://user-images.githubusercontent.com/38402428/101181194-e3ab4980-364c-11eb-918f-be5944e1df7b.PNG)

2.
![2_mta](https://user-images.githubusercontent.com/38402428/101181207-e7d76700-364c-11eb-95c0-4b7ee933e115.PNG)
![2_idea](https://user-images.githubusercontent.com/38402428/101181217-e9a12a80-364c-11eb-8c8a-84a91e763d21.PNG)

Open Models : 
[InccorectWelds.zip](https://github.com/idea-statica/iom-examples/files/5643581/InccorectWelds.zip)

**Comment by vojtech-chalupa** [comment]
Hello, thank you for reporting this. Indeed it looks like the an incorrect plate is connected by the weld in both cases (a web instead of a flange). I will keep you posted.

**Comment by dataneodev** [comment]
I tested beta version 21.0.0.0011 and still changing welds.

![image](https://user-images.githubusercontent.com/38402428/106172930-a7e7b880-6193-11eb-998d-3770c201c4df.png)

![image](https://user-images.githubusercontent.com/38402428/106173090-d8c7ed80-6193-11eb-9858-8bb29cda9460.png)

[OpenModel_h.zip](https://github.com/idea-statica/iom-examples/files/5888864/OpenModel_h.zip)

**Comment by vojtech-chalupa** [comment]
This issue is linked to [#26](https://github.com/idea-statica/ideastatica-public/issues/26), let's discuss the possible solution there.
