### ISSUE TITLE
[BUG] Tapered sections

### ISSUE THREAD

**Issue by johnnyontheweb** [idea-statica/iom-examples#63]
**Describe the bug**
I tapered section is not correctly treated inside IOM_IDEAConnectionRunner.exe:
1. IOM Wizard asks to merge elements 1 and 2, while they cannot be merged due to the tapered sections
2. tapered sections is not visible in Connection
3. Connections does not displayed correctly - node 2 is treated as an uniform section.

**To Reproduce**
Import with IOM_IDEAConnectionRunner.exe the attached file with standard settings.
[tapered.zip](https://github.com/idea-statica/iom-examples/files/5673754/tapered.zip)

**Screenshots**
![tapered](https://user-images.githubusercontent.com/10365055/101791403-c91d1880-3b03-11eb-8f2d-2b5d674ae238.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10-2004
 - IOM Version 20.1
 - IdeaStatiCa Version 20.1

**Comment by mpospisil** [comment]
IOM_IDEAConnectionRunner.exe - is obsolete. we do not support it anymore
Importing of tapered connection members  is not supported in our API. We solve only nearest connected part of the member in our CBFEM analysis.
But there is a workaround - you can a model tapered part of amember in IdeaConnection app - there is the manufacturing operation stub

**Comment by johnnyontheweb** [comment]
It seemed supported by idea.exe, see pic. Ok, I understand it's not supported, I think it must be specified in CrossSectionEnd in API.
