### ISSUE TITLE
[BUG] FlangeWidth in ColdFormedOmega section

### ISSUE THREAD

**Issue by johnnyontheweb** [idea-statica/iom-examples#64]
**Describe the bug**
The parameter FlangeWidth in CrossSectionFactory.FillColdFormedOmega method does not work as expected.

**To Reproduce**
Import this model using IOM_IDEAConnectionRunner.exe with standard settings.
[omega.zip](https://github.com/idea-statica/iom-examples/files/5673844/omega.zip)

**Expected behavior**
FlangeWidth has been set in XML as 0.1m. 
```
        <Parameter xsi:type="ParameterDouble">
          <Name>FlangeWidth</Name>
          <Value>0.1</Value>
        </Parameter>
```
I get a flange of 50mm.
![omega](https://user-images.githubusercontent.com/10365055/101793099-bc012900-3b05-11eb-8833-a65bc92dd145.PNG)

**Desktop (please complete the following information):**
 - OS: WIndows 2004
 - IOM Version 20.1
 - IdeaStatiCa Version 20.1

**Additional info**
by trials with the interface, it seems that only radius>=thickness is accepted for cold-formed beams. if it is so, this should be documented. Please disregard thickness in my sample, it's only for testing.

**Comment by mpospisil** [comment]
IOM_IDEAConnectionRunner.exe is obsolete - we don't support it anymore.
please update you link to be compatible with 

https://idea-statica.github.io/iom-examples/iom-steel-connections/cbfem-for-all.html
(direct link to idea connectection)

or our new CCM link
https://github.com/idea-statica/ccm-examples

**Comment by johnnyontheweb** [comment]
There are customers using 10.1 too. Anyway, is it sure the error is in IOM_IDEAConnectionRunner.exe??
I can't rewrite this right now, please reopen. Is it the only way to implement direct link?
