### ISSUE TITLE
[BUG] FlangeWidth in ColdFormedOmega section

### ISSUE THREAD

**Issue by johnnyontheweb** [idea-statica/iom-examples#65]
**Describe the bug**
The parameter FlangeWidth in CrossSectionFactory.FillColdFormedOmega method does not work as expected. Previously opened as #64.

**To Reproduce**
Import this model using FEAppExample_1 (CCM). This is an issue of IOM.
[modelBIM.zip](https://github.com/idea-statica/iom-examples/files/5677871/modelBIM.zip)

**Expected behavior**
FlangeWidth has been set in XML as 0.1m. 
```
        <Parameter xsi:type="ParameterDouble">
          <Name>FlangeWidth</Name>
          <Value>0.1</Value>
        </Parameter>
```
I get a flange of 50mm.
![omega](https://user-images.githubusercontent.com/10365055/101793099-bc012900-3b05-11eb-8833-a65bc92dd145.PNG)

**Desktop (please complete the following information):**
 - OS: WIndows 2004
 - IOM Version 20.1
 - IdeaStatiCa Version 20.1

**Additional context**
by trials with the interface, it seems that only radius>=thickness is accepted for cold-formed beams. if it is so, this should be documented. Please disregard thickness in my sample, it's only for testing.

**Comment by vojtech-chalupa** [comment]
The import should now produce a correct definition of a cold formed omega cross-section, with the latest release 21.0.0.3277

![image](https://user-images.githubusercontent.com/73105487/119132978-a93b3a80-ba3b-11eb-83b4-055e9cc71935.png)
