### ISSUE TITLE
[QUESTION] IDEA Connection project to XML

### ISSUE THREAD

**Issue by antonalabin** [idea-statica/iom-examples#67]
Is it possible to convert IDEA Connection project to XML files or OpenModel objects?

**Comment by mpospisil** [comment]
This feature will be available in the next release - version 21.
If you want we can provide you beta version for testing

**Comment by antonalabin** [comment]
> This feature will be available in the next release - version 21.
> If you want we can provide you beta version for testing

Yes. How can I install it?

**Comment by EricDuongED** [comment]
Hi Martin, 

Would it be possible to provide me with the beta version for testing as well?

**Comment by mpospisil** [comment]
Hi Eric,

There is the link to download IdeaStatiCa v21.0

https://jurajsabatkaideastatica-my.sharepoint.com/:f:/g/personal/martin_pospisil_ideastatica_com/EroHzeW45qVLn-VH0_YWTr4BVbhqL4aIK8py9cS-o8YUpw?e=85C0dn

it sould be compatible with the source code in the branch  release-21.0-beta
<https://github.com/idea-statica/iom-examples/tree/release-21.0-beta>

https://github.com/idea-statica/iom-examples/tree/release-21.0-beta
https://github.com/idea-statica/ccm-examples/tree/release-v21.0-beta

BR,
Martin

**Comment by EricDuongED** [comment]
Thanks so much Martin!

**Comment by mpospisil** [comment]
Hi Eric,
There is the latest v21.0 Beta

https://jurajsabatkaideastatica-my.sharepoint.com/:f:/g/personal/martin_pospisil_ideastatica_com/EnyVy8RZmedPghx0FcCwoP4BtmJpUuP0x9OTbpRiWP9o0A?e=Ee6Lf8

we will have to upadate your need licence. Send me details about your licence by email. 

Martin

**Comment by EricDuongED** [comment]
Hi Martin,

Where can I find you email?

**Comment by EricDuongED** [comment]
Hi Martin,

I'm using an educational license from the University of Alberta. My license
username is eduong1@ualberta.ca.

Cheers,
Eric
