### ISSUE TITLE
[QUESTION] GetAllConnectionData

### ISSUE THREAD

**Issue by antonalabin** [idea-statica/iom-examples#70]
Why methods GetAllConnectionData and GetConnectionModel from ConnectionHiddenCheckClient throwing errors, but method GetConnectionModelXML works fine?

**Comment by mpospisil** [comment]
You need to use nuget package for version 20.1

https://www.nuget.org/packages/IdeaStatiCa.Plugin/20.1.7

and examples from the branch release-20i

https://github.com/idea-statica/iom-examples/tree/release-20i

you are using the nuget package is for the new version IS  21 - which  is for our internal testing, that is why it doesn't work
