### ISSUE TITLE
[QUESTION] Сreate a project compatible with version 10

### ISSUE THREAD

**Issue by antonalabin** [idea-statica/iom-examples#71]
Is it possible in version 20 to create .ideaCon project compatible with version 10?

**Comment by TekuSP** [comment]
I don't think so, there were changes in ideaCon files from version 10 to version 20.
It's 100% possible other way around, in version 10 create file compatible with version 20.

I will ask my colleagues about this, and give you 100% answer.
Is it required feature for you? Why you want to create from newer application older project?
