### ISSUE TITLE
[QUESTION] Coping beams?

### ISSUE THREAD

**Issue by EricDuongED** [idea-statica/iom-examples#72]
Are you able to cope beams through the IOM? If so, how do you do it?

**Comment by vojtech-chalupa** [comment]
The best way to introduce copes is to use negative volumes - I've produced a simple example, where two RHS sections are used to cope the connected beam. A plate with a general outline and thickness can also be used as a negative volume (using the IsNegativeObject property).

[Cope.zip](https://github.com/idea-statica/iom-examples/files/5768705/Cope.zip)
