### ISSUE TITLE
[BUG] Issue with Negative Volume & CutBeamByBeam Operations affecting the IdeaCON File

### ISSUE THREAD

**Issue by EricDuongED** [idea-statica/iom-examples#73]
Hello, 

I've encountered a bug when creating negative volumes and CutBeamByBeam operations to cope my connections. When the IdeaCON file first loads, the CutBeambyBeam operations are not loaded into the file as shown below:

![image](https://user-images.githubusercontent.com/72173783/103984710-df3ee880-5144-11eb-9ba3-1613bc00b32e.png)

It isn't until the user clicks on the "Cut Beam by Beam" operations on the right that the file updates and you can see the correct connection detailing. 

![image](https://user-images.githubusercontent.com/72173783/103984828-12817780-5145-11eb-9d72-53f16f3c9dd0.png)

This creates a concern for me when I'm doing generative design as the evolutionary solver cannot run the CBFEM as it thinks there's a singularity with the file even though it's perfectly fine. 

I've attached the file in question along with the XML file here:
[Coped End Plate.zip](https://github.com/idea-statica/iom-examples/files/5785687/Coped.End.Plate.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - IOM Version: 21.0
 - IdeaStatiCa Version: 21.0 

Any help would be greatly appreciated!

Cheers,
Eric (University of Alberta Researcher)

**Comment by vojtech-chalupa** [comment]
Hello, I've replicated the issue on my side, we'll have a look at it and let you know.

**Comment by mpospisil** [comment]
bug in devop #2566

**Comment by vojtech-chalupa** [comment]
Eric, your issue can be solved by using a "Surface" value instead of "BoundingBox" value of the Method property in CutBeamByBeamData class, when cutting by a negative volume:
```
        <CutBeamByBeamData>
          <ModifiedObject>
            <TypeName>BeamData</TypeName>
            <Id>2</Id>
          </ModifiedObject>
          <CuttingObject>
            <TypeName>BeamData</TypeName>
            <Id>11</Id>
          </CuttingObject>
          <IsWeld>false</IsWeld>
          <WeldThickness>0</WeldThickness>
          <WeldType>NotSpecified</WeldType>
          <Offset>0</Offset>
          <Method>Surface</Method>
          <Orientation>Default</Orientation>
          <PlaneOnCuttingObject>Closer</PlaneOnCuttingObject>
        </CutBeamByBeamData>
```
You can notice that in the GUI, no option other than "Surface" is available for cuts by a negative volume. We will update the IOM documentation accordingly, so that this is clearly stated.
