### ISSUE TITLE
Where to find IdeaRcsController? [QUESTION]

### ISSUE THREAD

**Issue by mwdhont** [idea-statica/iom-examples#75]
Hi,

I'm trying to reproduce the following example: [RCS-column](https://idea-statica.github.io/iom-examples/rcs/rcs-column.html)
After installing the NuGet-package, everything goes fine, till the moment I reach the following code snippet:

```
//Creating instance of Rcs controller
var rcsController = new IdeaStatiCa.RcsController.IdeaRcsController();
System.Diagnostics.Debug.Assert(rcsController != null);

```
I can't find anything in the online documentation about the RcsController/IdeaRcsController and it's clearly not included in the NuGet-package neither. 

Could you please clarify where I can get the necessary?

Thanks,
Michiel

**Comment by TekuSP** [comment]
I will check with rest of development team and I will let you know, if this is a bug, or just wrong documentation or you are missing NuGet.
I will have response by Monday.

Enjoy your weekend.

Richard Torhan
Software Engineer

**Comment by TekuSP** [comment]
Transferring issue to Michal Číhal, it's bug in documentation.

**Comment by mcihal** [comment]
There is problem with the documentation. Calculation with the RCS  works in different way. Your application will call calculation core directly.
In your application add reference the IdeaStatiCa.RcsController.dll and IdeaRS.OpenModel.dll only. Both of them are in the Idea StatiCa instalation directory. (The IdeaRS.OpenModel.dll from the nuget can be used as well). For using this interface assembly the most of Idea dlls are needed. In the output directory (with your the exe app) the rest of Idea dlls must be copied as well. (or you can use a separate directory with Idea dlls and in the "yourapp".exe.setting must be configured the path of this directory)

We will change de documentation asap.

**Comment by mwdhont** [comment]
Hi Michal,

Thanks for the clarification. Could it be that IdeaStatiCa.RcsController.dll is not yet provided in the installation folder of version 10.1?

**Comment by mcihal** [comment]
The version 10.1. contains the IdeaStatiCa.RcsController.dll.
"C:\Program Files\IDEA StatiCa\StatiCa 10.1\IdeaStatiCa.RcsController.dll"

M.

**Comment by mwdhont** [comment]
Dear Michal,

We've checked at this location without success. See printscreen below.

However, we found the dll-file in the installation folder of version 20.0.104.
Still, I don't manage to finish the example. I've copied and referenced _IdeaStatiCa.RcsController.dll_ and _IdeaRS.OpenModel.dll_ in my VS project. Nevertheless, the error persists on the same location. 

I wonder if this could be related to the license, how does this work?


![RcsController v10 1](https://user-images.githubusercontent.com/53975317/106430681-70675d80-646c-11eb-95be-c1c2b2fdf074.png)

**Comment by mcihal** [comment]
Please download the newer version 10.1.177 from the https://www.ideastatica.com/product-downloads . 
For working the licence is necessary.

**Comment by kniazmajowiec** [comment]
Hi,

I am following the same example (RCS - column) and I have to admit that the concrete documentation is very limited.
I do believe that I am encountering the next step problem: 
Namely, I am using Idea version 20.1 and I was able to add IdeaRS.OpenModel and IdeaStatiCa.RcsController to the Dependencies of my project; however, while compiling the solution file I encounter the following issue: Unable to load DLL 'ShafferFilechck.DLL'. 
![missing_dll](https://user-images.githubusercontent.com/52321719/116249865-846de300-a76d-11eb-865e-5256357dd000.png)

This dll I cannot add to the dependencies as it is unsupported.

![unsupported_dll](https://user-images.githubusercontent.com/52321719/116250172-c565f780-a76d-11eb-820d-76096d637c65.png)

I have to admit that  I do not understand the proposed solution:
> There is problem with the documentation. Calculation with the RCS works in different way. Your application will call calculation core directly.
> In your application add reference the IdeaStatiCa.RcsController.dll and IdeaRS.OpenModel.dll only. Both of them are in the Idea StatiCa instalation directory. (The IdeaRS.OpenModel.dll from the nuget can be used as well). For using this interface assembly the most of Idea dlls are needed. In the output directory (with your the exe app) the rest of Idea dlls must be copied as well. (or you can use a separate directory with Idea dlls and in the "yourapp".exe.setting must be configured the path of this directory)
> 
> We will change de documentation asap.

I would appreciated a code snippet that resolves this issue or Nuget package of RcsController or even better working solution file with the concrete column.

Thank you in advance for your support.
Maciej

**Comment by mpospisil** [comment]
The IdeaStatica.RcsController must run in the same process as you application. This dll is depended an other libraries from idea instalation directory. So you have to create the link to the idea instalation directory in path where there is the your an exe aplication. 
for example in this way:

mklink /d idea "c:\Program Files\IDEA StatiCa\StatiCa 21.0"

This command creates virtual subdirectory next to your exe application.

In the confing file for you exe application (name.exe.config) you need to add this "probing" section inside assemblyBindings tag:

<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="idea" />
</assemblyBinding>

The file ShaferFilechk.dll in not necesarry to add as reference to your project. This solution automatically load all need dll from the idea instalation directory.
