### ISSUE TITLE
[BUG] in circular section, rotation angle set to 0 becomes 15°

### ISSUE THREAD

**Issue by johnnyontheweb** [idea-statica/iom-examples#76]
**Describe the bug**
Unexpected behaviour of IOM in Circle cross section definition: an angle of 15° is added!

**To Reproduce**
In IOM model, define a circle section with:
``` CrossSectionFactory.FillCircle(css3, 0.01) ```
an you'll get:
```
      <CrossSectionRotation>0</CrossSectionRotation>
      <CrossSectionType>O</CrossSectionType>
```

Unexpectedly, in IDEA Connection the section has 15° as angle of rotation.
![image_2021_01_20T19_07_12_061Z](https://user-images.githubusercontent.com/10365055/105319359-0bd31580-5bc5-11eb-843a-7715e8da7529.png)

**Expected behavior**
I expect rotation to be zero. This can create confusion on results processing (principal vs. local axes).

**Desktop (please complete the following information):**
 - OS: Windows 10 - latest
 - IOM Version 21.0.14.0 and all previous
 - IdeaStatiCa Version 20.1

**Comment by vojtech-chalupa** [comment]
Hello, thank you for your question. 
Speaking of "rod" cross-sections, this specific "alpha" angle doesn't specify the rotation of the CSS. It has to do with the discretization of circular cross-sections. In fact, this parameter is obsolete and I believe that it will be removed in the next release.

**Comment by johnnyontheweb** [comment]
This was truly unclear, now the drawing makes sense. I hope this would be removed, especially if this parameter cannot be controlled by IOM.
