### ISSUE TITLE
Getting member data information

### ISSUE THREAD

**Issue by torgrimw** [idea-statica/iom-examples#8]
Hi,
For a project I need to retrieve geometry data from the ideacon file. Based on your "ConnectionHiddenCalculation" example I am able to retrieve quite a lot of connection information. However - I am unable to retireve geometry information of i.e. members (vectors, points, cross sections for a member ....). Can you please guide me in the correct direction by adding an example or if it is already made - show me where it is. Thanks.

**Comment by mpospisil** [comment]
Look at properties of the class Plate

https://idea-statica.github.io/iom/iom-api/latest/html/fa62da56-78d0-ae76-ec1a-543e2b77497f.htm

Plates have own local coordinate system
Origin
AxisX
AxisY
AxisZ

and Region - Geometry of the plate in svg format

https://idea-statica.github.io/iom/iom-api/latest/html/8fd9c4a1-f34b-d663-7907-7454eeba7779.htm

you can use LCS of a plate for transformation its Region into the global system - 3D geometry

we will add an example
