### ISSUE TITLE
Importing Loading from a FEM software to IDEA Statica [QUESTION]

### ISSUE THREAD

**Issue by Fardadmokhtari** [idea-statica/iom-examples#80]
I am working with the API to import forces from a FEM software (S-Frame) to IDEA StatiCa. In the steel connection example, it was not described how the XML file was generated to be used to import the data into IDEA. I have the information (loads on each member) in an access database file (MDB). I can read this file using a c# code and store them in a proper data type. What is the best way to import them into IDEA? Should I create the XML file manually in C#? or is there a better way to tackle this problem?

Thank you,
Fardad

**Comment by mpospisil** [comment]
Hi Fardad,

it is described - see

https://github.com/idea-statica/iom-examples/blob/master/IOM_SteelFrame1/IOM.SteelFrameDesktop/Program.cs

you should create instance of [OpenModel ](https://idea-statica.github.io/iom/iom-api/latest/html/T_IdeaRS_OpenModel_OpenModel.htm).

This class has methods 

[SaveToXmlFile](https://idea-statica.github.io/iom/iom-api/latest/html/M_IdeaRS_OpenModel_OpenModel_SaveToXmlFile.htm)
[LoadFromXmlFile](https://idea-statica.github.io/iom/iom-api/latest/html/M_IdeaRS_OpenModel_OpenModel_LoadFromXmlFile.htm)
