### ISSUE TITLE
ConcreteBlock changes in 21.0.0.3277

### ISSUE THREAD

**Issue by jorgebslu** [idea-statica/iom-examples#86]
Hi,
I would like to ask you what has changed in concrete block definition in version 21.0.0.3277 respect to previous versions 20.1.5544.1 and 20.0.104.57553.
In the following screenshots I compare the concrete block position of the same [iom](https://github.com/idea-statica/iom-examples/files/6513118/iom.zip) in these 3 versions, and in the latest version (21.0.0.3277) the side of the concrete block and anchor bolts seem to be changed from previous versions:

1. In version 20.0.104.57553

![image](https://user-images.githubusercontent.com/66376954/118924004-c210f680-b93c-11eb-9785-0bbe669a5ffc.png)

2. In version 20.1.5544.1

![image](https://user-images.githubusercontent.com/66376954/118924179-00a6b100-b93d-11eb-9376-e61b1027b6e6.png)

3. In version 21.0.0.3277

![image](https://user-images.githubusercontent.com/66376954/118924683-ba058680-b93d-11eb-935f-5036d53564c6.png)

I would also like to request you to improve IOM about the definition of the concrete block where the anchor bolt are embedded. Currently there is a property `AnchorGrid.ConcreteBlock `with few properties that has "no relation" with `ConnectionData.ConcreteBlocks `where concrete blocks have a comprehensive definition.

BTW, could you provide help about what is the difference between `ConcreteBlockData.Origin` and  `ConcreteBlockData.Center` ?

![image](https://user-images.githubusercontent.com/66376954/118925189-968f0b80-b93e-11eb-9449-5d069f619df2.png)

I would like also to inform you that the `OriginalModelId` property is not fetched when I get the connection data from the current/active connection in `Code Check Manager`.

![image](https://user-images.githubusercontent.com/66376954/118925933-d4d8fa80-b93f-11eb-832d-15bcf5700aa4.png)

And also the name is lost.

Best regards
Jorge

**Comment by mpospisil** [comment]
Anchors are related to the coordinate system of the baseplate not to the concrete block.

**Comment by jorgebslu** [comment]
And concerning the concrete block itself and the other questions?
Thanks
Jorge

**Comment by vojtech-chalupa** [comment]
Hello, let me clarify this for you, sorry for the previous incomplete answer.
1) The reason for the change is that in version 21.0, the AnchorGrids and BoltGrids now have their own coordinate systems. When deciding the position of the concrete block, we take both coordinate systems (Plate and AnchorGrid) into account in the following manner:
`var dotNormals = WM.Vector3D.DotProduct(boltGridNormal, basePlateNormal);
if (dotNormals > 0)
{
connectorGridData.PlateSide = PlateSideCode.UpperSide;
}
else
{
connectorGridData.PlateSide = PlateSideCode.LowerSide;
}`
The best bet is to have them both in accordance with each other.

2) The whole ConcreteBlockData class is expendable for the purpose of import. It has been mostly used internally for the purpose of exporting the concrete block geometry itself (to .dwg for example). For your purpose, you only need to fill the AnchorGrid.ConcreteBlock data.

3) As for the missing properties, thank you for bringing that up, we'll look into it.

**Comment by vojtech-chalupa** [comment]
Closing this question, it is considered to be resolved. Feel free to reopen.
