### ISSUE TITLE
Potential wrong final shape of BeamData objects from cutting planes

### ISSUE THREAD

**Issue by jorgebslu** [idea-statica/iom-examples#89]
**BeamDatas / ConnectionBars seem to be incorrectly cut by cutting planes**

From attached [iom](https://github.com/idea-statica/iom-examples/files/6553433/d1f7e359-01c4-41e0-8817-1e2a7a0274ac-ModelBim-IOM.zip), try to export to `CodeCheckManager` v21.0.0.3277.
You will see that both haunches have a wrong final shape after applying cutting planes.
This issue could be related to #42 .

This is what I get in `IdeaConnection`:

![image](https://user-images.githubusercontent.com/66376954/119815346-b9479400-beeb-11eb-8cd3-c1aa41eacf36.png)

and this is what it should look like:

![image](https://user-images.githubusercontent.com/66376954/119815537-f449c780-beeb-11eb-9864-3f5bf4d225d3.png)

- OS: Windows 10 Pro-1909
- IOM Version 21.0.0.3277
- IdeaStatiCa Version 21.0.0.3277

Thanks
Jorge

**Comment by vojtech-chalupa** [comment]
Hello, this is an issue with the CUT operation itself applied on stiffening members, the IOM is correct. It has been partially fixed in 21.0.0.2340, but your case still causes issues, thanks for reporting this. I am sending this to be fixed in the next patch.

**Comment by vojtech-chalupa** [comment]
The patch has [21.0.2.1036 ](https://www.ideastatica.com/product-downloads) has now been released, your issue should be fixed. Can you confirm? Thank you.
