### ISSUE TITLE
Missing weld data

### ISSUE THREAD

**Issue by errone92** [idea-statica/iom-examples#9]
Hello, I noticed that in the WeldData class sometimes the ConnectedPartId properties are missing data. Particularly I am looking at a connection where there is a stub that is cut by a circular section column and welded. But the ConnectedPartIds are empty when it should show the column and the stub plates. Is this a limitation of the API at the moment?

**Comment by mpospisil** [comment]
Can you send me a idea connection project to be able to reproduce it ?

**Comment by errone92** [comment]
Here's the file:

[RoundConnectionTest.zip](https://github.com/idea-statica/iom-examples/files/3977320/RoundConnectionTest.zip)

**Comment by mpospisil** [comment]
you are right - we are not writing this information into welddata
we will add it into development

**Comment by errone92** [comment]
Ok thank you. Keep me updated.

**Comment by mpospisil** [comment]
it should be fixed in the beta version 20.0
