### ISSUE TITLE
IdeaStatiCaAppClient.GetCssInMPRL returns same library items for any CountryCode

### ISSUE THREAD

**Issue by jorgebslu** [idea-statica/iom-examples#90]
Hi,
We need to map MPRL items with our items (materials and sections).
I was checking  `IdeaStatiCaAppClient.GetCssInMPRL` method and I realized that this method always returns the same list (26799 items) of `LibraryItem` regardless the input `CountryCode` I provide.
That is not the case for `IdeaStatiCaAppClient.GetMaterialsInMPRL` that returns the corresponding materials for the input argument `CountryCode`.
My question is, Am I doing anything wrong when I call `GetCssInMPRL` method? Or `CountryCode` is ignored? Or there is a bug in that method's implementation?

FYI, for testing, I am using the commands that are defined in your example [FEAppTestVM](https://github.com/idea-statica/ideastatica-public/blob/main/src/Examples/CCM/FEAppExample_1/FEAppTestVM.cs).

 * [GetCssInMPRL](https://github.com/idea-statica/ideastatica-public/blob/ca979035a2e32289fa9d3397da55b8e489f3b36b/src/Examples/CCM/FEAppExample_1/FEAppTestVM.cs#L507)
 * [GetMaterialsInMPRL](https://github.com/idea-statica/ideastatica-public/blob/ca979035a2e32289fa9d3397da55b8e489f3b36b/src/Examples/CCM/FEAppExample_1/FEAppTestVM.cs#L408)
 
I will appreciate any help on this topic.
Best regards
Jorge

FYI, this issue happens in versions 21.0 and 20.1

**Comment by jorgebslu** [comment]
I would also like to make another questions.
By taking a look at the output for Css and Materials from MPRL, I detect
![image](https://user-images.githubusercontent.com/66376954/121176676-c86c0180-c85c-11eb-8665-5af6d85b381d.png)

* For Cross-sections, I see that both "Identifier" and "GroupId" are the same for all cross-sections from the same family/group.
I thought that "Identifier" was behaving as a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier), but I cannot consider that assumption because I cannot uniquely identify a cross-section by its "Identifier". Does it mean I have to use the "Name" as the identifier (por mapping purpose) and trust that names are not repeated for the 26799 items ?
* For Materials, every material has its own "Identifier", which sounds logical for me:

  ![image](https://user-images.githubusercontent.com/66376954/121176301-5693b800-c85c-11eb-923e-0f62db72e2bc.png)

  ![image](https://user-images.githubusercontent.com/66376954/121176410-788d3a80-c85c-11eb-8740-3883574075a1.png)

**Comment by vojtech-chalupa** [comment]
Hello, to answer your first question - the cross-sections are indeed CountryCode independent, so it is ignored when calling GetCssInMprl. Materials, however, are CountryCode dependant, mainly because of code-specific properties.

**Comment by jorgebslu** [comment]
Hi Vojtech,
Is `IdeaConnection` considering `CountryCode` for the available/allowed CSS that a user can use for members? If so, now it is not possible to get the allowed CSS from that method for a given `CountryCode` because I will get all of them, regardless the value of `CountryCode`, and afterwards, user will have problems in `IdeaConnection`.

And concerning the repeated `Identifiers` for all CSS from the same Family/Group ?
Is the `Name` what I should use for mapping ?

Thank you in advance.
Jorge

**Comment by vojtech-chalupa** [comment]
IdeaConnection is not considering CoutnryCode for the availability of cross-sections. Any cross-section can be used in any code.
As for the identifiers, I am trying to get you the answer as we speak - what the best practice for mapping is.

**Comment by vojtech-chalupa** [comment]
Regarding your second question - when filling the IOM, the "name" string is the unique value to use for mapping and is enough for import to go through.

The other values (identifier and groupId) presented through GetCssInMprl are related to the cross-section group and table in the MPRL (e.g. all Rolled I sections are in the same group = have the same "groupId", all "HEA" sections are in the same table and have the same "identifier"). All our links, however, are based on "name".

**Comment by vojtech-chalupa** [comment]
Closing this question, it is considered to be resolved. Feel free to reopen.
